import { Extension, textInputRule } from '@tiptap/core'

export const SmilieReplacer = Extension.create({
    name: 'smilieReplacer',

    addInputRules() {
        return [
            textInputRule({ find: /:rocket: $/, replace: '🚀 ' }),
            textInputRule({ find: /:fire: $/, replace: '🔥 ' }),
            textInputRule({ find: /:heart_eyes: $/, replace: '😍 ' }),
            textInputRule({ find: /:heart_eyes_cat: $/, replace: '😻 ' }),
            textInputRule({ find: /:heart_eyes_dog: $/, replace: '🐶 ' }),
            textInputRule({ find: /:heart_eyes_pig: $/, replace: '🐷 ' }),
            textInputRule({ find: /:heart_eyes_monkey: $/, replace: '🐵 ' }),
            textInputRule({ find: /:heart_eyes_panda: $/, replace: '🐼 ' }),
            textInputRule({ find: /:heart_eyes_bear: $/, replace: '🐻 ' }),
            textInputRule({ find: /:heart_eyes_penguin: $/, replace: '🐧 ' }),
            textInputRule({ find: /:heart_eyes_chick: $/, replace: '🐥 ' }),
            textInputRule({ find: /:heart_eyes_bird: $/, replace: '🐦 ' }),
            textInputRule({ find: /:heart_eyes_fish: $/, replace: '🐠 ' }),
            textInputRule({ find: /:heart_eyes_whale: $/, replace: '🐳 ' }),
            textInputRule({ find: /:heart_eyes_turtle: $/, replace: '🐢 ' }),
            textInputRule({ find: /:heart_eyes_bee: $/, replace: '🐝 ' }),
            textInputRule({ find: /:heart_eyes_butterfly: $/, replace: '🦋 ' }),
            textInputRule({ find: /:heart_eyes_flower: $/, replace: '🌺 ' }),
            textInputRule({ find: /:heart_eyes_tree: $/, replace: '🌳 ' }),
            textInputRule({ find: /:heart_eyes_sun: $/, replace: '🌞 ' }),
            textInputRule({ find: /:heart_eyes_cloud: $/, replace: '☁️ ' }),
            textInputRule({ find: /:heart_eyes_rain: $/, replace: '🌧️ ' }),
            textInputRule({ find: /:heart_eyes_snow: $/, replace: '❄️ ' }),
            textInputRule({ find: /:heart_eyes_moon: $/, replace: '🌙 ' }),
            textInputRule({ find: /:heart_eyes_star: $/, replace: '⭐ ' }),
            textInputRule({ find: /:heart_eyes_earth: $/, replace: '🌍 ' }),
            textInputRule({ find: /:heart_eyes_mars: $/, replace: '🪐 ' }),
            textInputRule({ find: /:heart_eyes_saturn: $/, replace: '🪐 ' }),
            textInputRule({ find: /:heart_eyes_galaxy: $/, replace: '🌌 ' }),
            textInputRule({ find: /:heart_eyes_sunflower: $/, replace: '🌻 ' }),
            textInputRule({ find: /:heart_eyes_rose: $/, replace: '🌹 ' }),
            textInputRule({ find: /:heart_eyes_tulip: $/, replace: '🌷 ' }),
            textInputRule({ find: /:heart_eyes_daisy: $/, replace: '🌼 ' }),
            textInputRule({ find: /:chart: $/, replace: '📈 ' }),
            textInputRule({ find: /:tada: $/, replace: '🎉 ' }),
            textInputRule({ find: /:bulb: $/, replace: '💡 ' }),
            textInputRule({ find: /:money: $/, replace: '💰 ' }),
            textInputRule({ find: /:100: $/, replace: '💯 ' }),
            textInputRule({ find: /:star: $/, replace: '⭐ ' }),
            textInputRule({ find: /:zap: $/, replace: '⚡ ' }),
            textInputRule({ find: /:boom: $/, replace: '💥 ' }),
            textInputRule({ find: /:clap: $/, replace: '👏 ' }),
            textInputRule({ find: /:muscle: $/, replace: '💪 ' }),
            textInputRule({ find: /:cool: $/, replace: '😎 ' }),
            textInputRule({ find: /:thinking: $/, replace: '🤔 ' }),
            textInputRule({ find: /:sweat_smile: $/, replace: '😅 ' }),
            textInputRule({ find: /:grinning: $/, replace: '😁 ' }),
            textInputRule({ find: /:cry: $/, replace: '😭 ' }),
            textInputRule({ find: /:skull: $/, replace: '💀 ' }),
            textInputRule({ find: /:poop: $/, replace: '💩 ' }),
            textInputRule({ find: /:shrug: $/, replace: '¯\\_(ツ)_/¯ ' }),
            textInputRule({ find: /:smile: $/, replace: '😊 ' }),
            textInputRule({ find: /:thumbsup: $/, replace: '👍 ' }),
            textInputRule({ find: /:thumbsdown: $/, replace: '👎 ' }),
            textInputRule({ find: /:pray: $/, replace: '🙏 ' }),
            textInputRule({ find: /:heart: $/, replace: '❤️ ' }),
            textInputRule({ find: /:broken_heart: $/, replace: '💔 ' }),
            textInputRule({ find: /:facepalm: $/, replace: '🤦 ' }),
            textInputRule({ find: /:ok_hand: $/, replace: '👌 ' }),
            textInputRule({ find: /:running: $/, replace: '🏃 ' }),
            textInputRule({ find: /:yoga: $/, replace: '🧘 ' }),
            textInputRule({ find: /:meditation: $/, replace: '🧘‍♂️ ' }),
            textInputRule({ find: /:avocado: $/, replace: '🥑 ' }),
            textInputRule({ find: /:croissant: $/, replace: '🥐 ' }),
            textInputRule({ find: /:bitcoin: $/, replace: '₿ ' }),
            textInputRule({ find: /:ethereum: $/, replace: 'Ξ ' }),
            textInputRule({ find: /:dogecoin: $/, replace: 'Ð ' }),
            textInputRule({ find: /:solana: $/, replace: '◎ ' }),
            textInputRule({ find: /:cardano: $/, replace: '₳ ' }),
            textInputRule({ find: /:moneybag: $/, replace: '💰 ' }),
            textInputRule({ find: /:money_with_wings: $/, replace: '💸 ' }),
            textInputRule({ find: /:dollar: $/, replace: '💵 ' }),
            textInputRule({ find: /:yen: $/, replace: '💴 ' }),
            textInputRule({ find: /:euro: $/, replace: '💶 ' }),
            textInputRule({ find: /:pound: $/, replace: '💷 ' }),
            textInputRule({ find: /:robot: $/, replace: '🤖 ' }),
            textInputRule({ find: /:alien: $/, replace: '👽 ' }),
            textInputRule({ find: /:coffee: $/, replace: '☕ ' }),
            textInputRule({ find: /:pizza: $/, replace: '🍕 ' }),
            textInputRule({ find: /:beer: $/, replace: '🍺 ' }),
            textInputRule({ find: /:champagne: $/, replace: '🍾 ' }),
        ]
    },
})
