/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Actions = {
    SentInvite: 'SENT_INVITE',
    Referral: 'REFERRAL',
    FiveLikes: 'FIVE_LIKES',
    ThreeComments: 'THREE_COMMENTS',
    CompletedGoal: 'COMPLETED_GOAL',
    JoinedCommunity: 'JOINED_COMMUNITY',
    FirstPost: 'FIRST_POST',
    FirstComment: 'FIRST_COMMENT',
    CreatedCommunity: 'CREATED_COMMUNITY',
    Like: 'LIKE',
    Comment: 'COMMENT',
    Post: 'POST',
    Joined: 'JOINED',
    Invite: 'INVITE',
    DailyVisit: 'DAILY_VISIT',
    Oinkd: 'OINKD'
} as const;
export type Actions = typeof Actions[keyof typeof Actions];


export function instanceOfActions(value: any): boolean {
    for (const key in Actions) {
        if (Object.prototype.hasOwnProperty.call(Actions, key)) {
            if (Actions[key as keyof typeof Actions] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActionsFromJSON(json: any): Actions {
    return ActionsFromJSONTyped(json, false);
}

export function ActionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Actions {
    return json as Actions;
}

export function ActionsToJSON(value?: Actions | null): any {
    return value as any;
}

export function ActionsToJSONTyped(value: any, ignoreDiscriminator: boolean): Actions {
    return value as Actions;
}

