/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object describing the amount, could be used for prices and balances.
 * @export
 * @interface Amount
 */
export interface Amount {
    /**
     * 
     * @type {number}
     * @memberof Amount
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Amount
     */
    currency?: AmountCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof Amount
     */
    crypto?: AmountCryptoEnum;
}


/**
 * @export
 */
export const AmountCurrencyEnum = {
    Usd: 'USD',
    Eur: 'EUR'
} as const;
export type AmountCurrencyEnum = typeof AmountCurrencyEnum[keyof typeof AmountCurrencyEnum];

/**
 * @export
 */
export const AmountCryptoEnum = {
    Btc: 'BTC',
    Base: 'BASE',
    Eth: 'ETH',
    Sol: 'SOL'
} as const;
export type AmountCryptoEnum = typeof AmountCryptoEnum[keyof typeof AmountCryptoEnum];


/**
 * Check if a given object implements the Amount interface.
 */
export function instanceOfAmount(value: object): value is Amount {
    return true;
}

export function AmountFromJSON(json: any): Amount {
    return AmountFromJSONTyped(json, false);
}

export function AmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Amount {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'crypto': json['crypto'] == null ? undefined : json['crypto'],
    };
}

export function AmountToJSON(json: any): Amount {
    return AmountToJSONTyped(json, false);
}

export function AmountToJSONTyped(value?: Amount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'crypto': value['crypto'],
    };
}

