/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Badge
 */
export interface Badge {
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the Badge interface.
 */
export function instanceOfBadge(value: object): value is Badge {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function BadgeFromJSON(json: any): Badge {
    return BadgeFromJSONTyped(json, false);
}

export function BadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Badge {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function BadgeToJSON(json: any): Badge {
    return BadgeToJSONTyped(json, false);
}

export function BadgeToJSONTyped(value?: Badge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
    };
}

