/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * The bank account number.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber: string;
    /**
     * The bank routing number.
     * @type {string}
     * @memberof BankAccount
     */
    routingNumber: string;
    /**
     * The type of bank account.
     * @type {string}
     * @memberof BankAccount
     */
    accountType: BankAccountAccountTypeEnum;
    /**
     * The name of the bank.
     * @type {string}
     * @memberof BankAccount
     */
    bankName: string;
    /**
     * The name of the account holder.
     * @type {string}
     * @memberof BankAccount
     */
    accountHolderName: string;
    /**
     * The currency of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    currency: string;
}


/**
 * @export
 */
export const BankAccountAccountTypeEnum = {
    Checking: 'CHECKING',
    Savings: 'SAVINGS'
} as const;
export type BankAccountAccountTypeEnum = typeof BankAccountAccountTypeEnum[keyof typeof BankAccountAccountTypeEnum];


/**
 * Check if a given object implements the BankAccount interface.
 */
export function instanceOfBankAccount(value: object): value is BankAccount {
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('routingNumber' in value) || value['routingNumber'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('bankName' in value) || value['bankName'] === undefined) return false;
    if (!('accountHolderName' in value) || value['accountHolderName'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function BankAccountFromJSON(json: any): BankAccount {
    return BankAccountFromJSONTyped(json, false);
}

export function BankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNumber': json['accountNumber'],
        'routingNumber': json['routingNumber'],
        'accountType': json['accountType'],
        'bankName': json['bankName'],
        'accountHolderName': json['accountHolderName'],
        'currency': json['currency'],
    };
}

export function BankAccountToJSON(json: any): BankAccount {
    return BankAccountToJSONTyped(json, false);
}

export function BankAccountToJSONTyped(value?: BankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountNumber': value['accountNumber'],
        'routingNumber': value['routingNumber'],
        'accountType': value['accountType'],
        'bankName': value['bankName'],
        'accountHolderName': value['accountHolderName'],
        'currency': value['currency'],
    };
}

