/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAccount1
 */
export interface BankAccount1 {
    /**
     * The bank account number.
     * @type {string}
     * @memberof BankAccount1
     */
    accountNumber: string;
    /**
     * The bank routing number.
     * @type {string}
     * @memberof BankAccount1
     */
    routingNumber: string;
    /**
     * The type of bank account.
     * @type {string}
     * @memberof BankAccount1
     */
    accountType: BankAccount1AccountTypeEnum;
    /**
     * The name of the bank.
     * @type {string}
     * @memberof BankAccount1
     */
    bankName: string;
    /**
     * The name of the account holder.
     * @type {string}
     * @memberof BankAccount1
     */
    accountHolderName: string;
    /**
     * The currency of the bank account.
     * @type {string}
     * @memberof BankAccount1
     */
    currency: string;
}


/**
 * @export
 */
export const BankAccount1AccountTypeEnum = {
    Checking: 'CHECKING',
    Savings: 'SAVINGS'
} as const;
export type BankAccount1AccountTypeEnum = typeof BankAccount1AccountTypeEnum[keyof typeof BankAccount1AccountTypeEnum];


/**
 * Check if a given object implements the BankAccount1 interface.
 */
export function instanceOfBankAccount1(value: object): value is BankAccount1 {
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('routingNumber' in value) || value['routingNumber'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('bankName' in value) || value['bankName'] === undefined) return false;
    if (!('accountHolderName' in value) || value['accountHolderName'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function BankAccount1FromJSON(json: any): BankAccount1 {
    return BankAccount1FromJSONTyped(json, false);
}

export function BankAccount1FromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccount1 {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNumber': json['accountNumber'],
        'routingNumber': json['routingNumber'],
        'accountType': json['accountType'],
        'bankName': json['bankName'],
        'accountHolderName': json['accountHolderName'],
        'currency': json['currency'],
    };
}

export function BankAccount1ToJSON(json: any): BankAccount1 {
    return BankAccount1ToJSONTyped(json, false);
}

export function BankAccount1ToJSONTyped(value?: BankAccount1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountNumber': value['accountNumber'],
        'routingNumber': value['routingNumber'],
        'accountType': value['accountType'],
        'bankName': value['bankName'],
        'accountHolderName': value['accountHolderName'],
        'currency': value['currency'],
    };
}

