/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Blog
 */
export interface Blog {
    /**
     * The title of the blog.
     * @type {string}
     * @memberof Blog
     */
    title: string;
    /**
     * The subtitle of the blog.
     * @type {string}
     * @memberof Blog
     */
    subtitle?: string;
    /**
     * The content of the blog.
     * @type {string}
     * @memberof Blog
     */
    content: string;
    /**
     * The unique identifier for the community.
     * @type {string}
     * @memberof Blog
     */
    communityId: string;
    /**
     * The slug of the blog.
     * @type {string}
     * @memberof Blog
     */
    slug: string;
    /**
     * The unique identifier for the author.
     * @type {string}
     * @memberof Blog
     */
    authorId: string;
    /**
     * The image of the blog.
     * @type {string}
     * @memberof Blog
     */
    coverPhoto?: string;
    /**
     * The tags of the blog.
     * @type {Array<string>}
     * @memberof Blog
     */
    tags?: Array<string>;
    /**
     * The draft status of the blog.
     * @type {boolean}
     * @memberof Blog
     */
    draft?: boolean;
    /**
     * The date and time when the blog was published.
     * @type {string}
     * @memberof Blog
     */
    createdAt?: string;
    /**
     * The date and time when the blog was last updated.
     * @type {Date}
     * @memberof Blog
     */
    modifiedAt?: Date;
    /**
     * The unique identifier for the post.
     * @type {string}
     * @memberof Blog
     */
    postId?: string;
    /**
     * The profile picture of the author.
     * @type {string}
     * @memberof Blog
     */
    authorProfilePic?: string;
    /**
     * The IPFS hash of the blog.
     * @type {string}
     * @memberof Blog
     */
    ipfsHash?: string;
    /**
     * The unique identifier for the blog.
     * @type {string}
     * @memberof Blog
     */
    id?: string;
}

/**
 * Check if a given object implements the Blog interface.
 */
export function instanceOfBlog(value: object): value is Blog {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('communityId' in value) || value['communityId'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    return true;
}

export function BlogFromJSON(json: any): Blog {
    return BlogFromJSONTyped(json, false);
}

export function BlogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Blog {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'content': json['content'],
        'communityId': json['communityId'],
        'slug': json['slug'],
        'authorId': json['authorId'],
        'coverPhoto': json['coverPhoto'] == null ? undefined : json['coverPhoto'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'draft': json['draft'] == null ? undefined : json['draft'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
        'postId': json['postId'] == null ? undefined : json['postId'],
        'authorProfilePic': json['authorProfilePic'] == null ? undefined : json['authorProfilePic'],
        'ipfsHash': json['ipfsHash'] == null ? undefined : json['ipfsHash'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function BlogToJSON(json: any): Blog {
    return BlogToJSONTyped(json, false);
}

export function BlogToJSONTyped(value?: Blog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'subtitle': value['subtitle'],
        'content': value['content'],
        'communityId': value['communityId'],
        'slug': value['slug'],
        'authorId': value['authorId'],
        'coverPhoto': value['coverPhoto'],
        'tags': value['tags'],
        'draft': value['draft'],
        'createdAt': value['createdAt'],
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
        'postId': value['postId'],
        'authorProfilePic': value['authorProfilePic'],
        'ipfsHash': value['ipfsHash'],
        'id': value['id'],
    };
}

