/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkEmailResponse
 */
export interface BulkEmailResponse {
    /**
     * Whether the bulk email operation was successful
     * @type {boolean}
     * @memberof BulkEmailResponse
     */
    success?: boolean;
    /**
     * Success or error message
     * @type {string}
     * @memberof BulkEmailResponse
     */
    message?: string;
    /**
     * Number of emails successfully sent
     * @type {number}
     * @memberof BulkEmailResponse
     */
    emailsSent?: number;
    /**
     * Total number of attendees found for the event
     * @type {number}
     * @memberof BulkEmailResponse
     */
    totalAttendees?: number;
    /**
     * List of email addresses that failed to send
     * @type {Array<string>}
     * @memberof BulkEmailResponse
     */
    failedEmails?: Array<string>;
    /**
     * The event slot ID that emails were sent for
     * @type {string}
     * @memberof BulkEmailResponse
     */
    eventSlotId?: string;
}

/**
 * Check if a given object implements the BulkEmailResponse interface.
 */
export function instanceOfBulkEmailResponse(value: object): value is BulkEmailResponse {
    return true;
}

export function BulkEmailResponseFromJSON(json: any): BulkEmailResponse {
    return BulkEmailResponseFromJSONTyped(json, false);
}

export function BulkEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'emailsSent': json['emailsSent'] == null ? undefined : json['emailsSent'],
        'totalAttendees': json['totalAttendees'] == null ? undefined : json['totalAttendees'],
        'failedEmails': json['failedEmails'] == null ? undefined : json['failedEmails'],
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
    };
}

export function BulkEmailResponseToJSON(json: any): BulkEmailResponse {
    return BulkEmailResponseToJSONTyped(json, false);
}

export function BulkEmailResponseToJSONTyped(value?: BulkEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'emailsSent': value['emailsSent'],
        'totalAttendees': value['totalAttendees'],
        'failedEmails': value['failedEmails'],
        'eventSlotId': value['eventSlotId'],
    };
}

