/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Category = {
    CreditCard: 'CREDIT_CARD',
    SavingsAccount: 'SAVINGS_ACCOUNT',
    HomeLoan: 'HOME_LOAN',
    PersonalLoan: 'PERSONAL_LOAN',
    CarLoan: 'CAR_LOAN',
    EducationLoan: 'EDUCATION_LOAN',
    Insurance: 'INSURANCE',
    Crypto: 'CRYPTO',
    Stocks: 'STOCKS',
    MutualFunds: 'MUTUAL_FUNDS',
    IraAccount: 'IRA_ACCOUNT',
    _401KAccount: '401K_ACCOUNT',
    RetirementAccount: 'RETIREMENT_ACCOUNT',
    Misc: 'MISC'
} as const;
export type Category = typeof Category[keyof typeof Category];


export function instanceOfCategory(value: any): boolean {
    for (const key in Category) {
        if (Object.prototype.hasOwnProperty.call(Category, key)) {
            if (Category[key as keyof typeof Category] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    return json as Category;
}

export function CategoryToJSON(value?: Category | null): any {
    return value as any;
}

export function CategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): Category {
    return value as Category;
}

