/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckEventsV2Reminders200Response
 */
export interface CheckEventsV2Reminders200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CheckEventsV2Reminders200Response
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CheckEventsV2Reminders200Response
     */
    eventsProcessed?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckEventsV2Reminders200Response
     */
    totalEmailsSent?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckEventsV2Reminders200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the CheckEventsV2Reminders200Response interface.
 */
export function instanceOfCheckEventsV2Reminders200Response(value: object): value is CheckEventsV2Reminders200Response {
    return true;
}

export function CheckEventsV2Reminders200ResponseFromJSON(json: any): CheckEventsV2Reminders200Response {
    return CheckEventsV2Reminders200ResponseFromJSONTyped(json, false);
}

export function CheckEventsV2Reminders200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEventsV2Reminders200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'eventsProcessed': json['eventsProcessed'] == null ? undefined : json['eventsProcessed'],
        'totalEmailsSent': json['totalEmailsSent'] == null ? undefined : json['totalEmailsSent'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CheckEventsV2Reminders200ResponseToJSON(json: any): CheckEventsV2Reminders200Response {
    return CheckEventsV2Reminders200ResponseToJSONTyped(json, false);
}

export function CheckEventsV2Reminders200ResponseToJSONTyped(value?: CheckEventsV2Reminders200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'eventsProcessed': value['eventsProcessed'],
        'totalEmailsSent': value['totalEmailsSent'],
        'message': value['message'],
    };
}

