/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientErrorContextInfo } from './ClientErrorContextInfo';
import {
    ClientErrorContextInfoFromJSON,
    ClientErrorContextInfoFromJSONTyped,
    ClientErrorContextInfoToJSON,
    ClientErrorContextInfoToJSONTyped,
} from './ClientErrorContextInfo';

/**
 * A generic error
 * @export
 * @interface ClientError
 */
export interface ClientError {
    /**
     * `error`
     * @type {string}
     * @memberof ClientError
     */
    type?: ClientErrorTypeEnum;
    /**
     * The HTTP status of the response.
     * @type {number}
     * @memberof ClientError
     */
    status?: number;
    /**
     * A Box-specific error code
     * @type {string}
     * @memberof ClientError
     */
    code?: ClientErrorCodeEnum;
    /**
     * A short message describing the error.
     * @type {string}
     * @memberof ClientError
     */
    message?: string;
    /**
     * 
     * @type {ClientErrorContextInfo}
     * @memberof ClientError
     */
    contextInfo?: ClientErrorContextInfo;
    /**
     * A URL that links to more information about why this error occurred.
     * @type {string}
     * @memberof ClientError
     */
    helpUrl?: string;
    /**
     * A unique identifier for this response, which can be used
     * when contacting Box support.
     * @type {string}
     * @memberof ClientError
     */
    requestId?: string;
}


/**
 * @export
 */
export const ClientErrorTypeEnum = {
    Error: 'error'
} as const;
export type ClientErrorTypeEnum = typeof ClientErrorTypeEnum[keyof typeof ClientErrorTypeEnum];

/**
 * @export
 */
export const ClientErrorCodeEnum = {
    Created: 'created',
    Accepted: 'accepted',
    NoContent: 'no_content',
    Redirect: 'redirect',
    NotModified: 'not_modified',
    BadRequest: 'bad_request',
    Unauthorized: 'unauthorized',
    Forbidden: 'forbidden',
    NotFound: 'not_found',
    MethodNotAllowed: 'method_not_allowed',
    Conflict: 'conflict',
    PreconditionFailed: 'precondition_failed',
    TooManyRequests: 'too_many_requests',
    InternalServerError: 'internal_server_error',
    Unavailable: 'unavailable',
    ItemNameInvalid: 'item_name_invalid',
    InsufficientScope: 'insufficient_scope'
} as const;
export type ClientErrorCodeEnum = typeof ClientErrorCodeEnum[keyof typeof ClientErrorCodeEnum];


/**
 * Check if a given object implements the ClientError interface.
 */
export function instanceOfClientError(value: object): value is ClientError {
    return true;
}

export function ClientErrorFromJSON(json: any): ClientError {
    return ClientErrorFromJSONTyped(json, false);
}

export function ClientErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientError {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'contextInfo': json['context_info'] == null ? undefined : ClientErrorContextInfoFromJSON(json['context_info']),
        'helpUrl': json['help_url'] == null ? undefined : json['help_url'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ClientErrorToJSON(json: any): ClientError {
    return ClientErrorToJSONTyped(json, false);
}

export function ClientErrorToJSONTyped(value?: ClientError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'context_info': ClientErrorContextInfoToJSON(value['contextInfo']),
        'help_url': value['helpUrl'],
        'request_id': value['requestId'],
    };
}

