/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A free-form object that contains additional context
 * about the error. The possible fields are defined on
 * a per-endpoint basis. `message` is only one example.
 * @export
 * @interface ClientErrorContextInfo
 */
export interface ClientErrorContextInfo {
    /**
     * More details on the error.
     * @type {string}
     * @memberof ClientErrorContextInfo
     */
    message?: string;
}

/**
 * Check if a given object implements the ClientErrorContextInfo interface.
 */
export function instanceOfClientErrorContextInfo(value: object): value is ClientErrorContextInfo {
    return true;
}

export function ClientErrorContextInfoFromJSON(json: any): ClientErrorContextInfo {
    return ClientErrorContextInfoFromJSONTyped(json, false);
}

export function ClientErrorContextInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientErrorContextInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ClientErrorContextInfoToJSON(json: any): ClientErrorContextInfo {
    return ClientErrorContextInfoToJSONTyped(json, false);
}

export function ClientErrorContextInfoToJSONTyped(value?: ClientErrorContextInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

