/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunityOnboardingQuestion } from './CommunityOnboardingQuestion';
import {
    CommunityOnboardingQuestionFromJSON,
    CommunityOnboardingQuestionFromJSONTyped,
    CommunityOnboardingQuestionToJSON,
    CommunityOnboardingQuestionToJSONTyped,
} from './CommunityOnboardingQuestion';

/**
 * 
 * @export
 * @interface CommunityRules
 */
export interface CommunityRules {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityRules
     */
    adminUserId: string;
    /**
     * The unique identifier for the community.
     * @type {string}
     * @memberof CommunityRules
     */
    id: string;
    /**
     * The rules of the community.
     * @type {string}
     * @memberof CommunityRules
     */
    rules: string;
    /**
     * Whether the community requires approval to join.
     * @type {boolean}
     * @memberof CommunityRules
     */
    requiresApproval?: boolean;
    /**
     * Whether the community requires payment to join.
     * @type {boolean}
     * @memberof CommunityRules
     */
    requiresPaidSubscription?: boolean;
    /**
     * Whether the community requires login to view.
     * @type {boolean}
     * @memberof CommunityRules
     */
    requiresLogin?: boolean;
    /**
     * The questions of the community.
     * @type {Array<CommunityOnboardingQuestion>}
     * @memberof CommunityRules
     */
    onboardingQuestions?: Array<CommunityOnboardingQuestion>;
    /**
     * The list of banned users.
     * @type {Array<string>}
     * @memberof CommunityRules
     */
    bannedUsers?: Array<string>;
}

/**
 * Check if a given object implements the CommunityRules interface.
 */
export function instanceOfCommunityRules(value: object): value is CommunityRules {
    if (!('adminUserId' in value) || value['adminUserId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function CommunityRulesFromJSON(json: any): CommunityRules {
    return CommunityRulesFromJSONTyped(json, false);
}

export function CommunityRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityRules {
    if (json == null) {
        return json;
    }
    return {
        
        'adminUserId': json['adminUserId'],
        'id': json['id'],
        'rules': json['rules'],
        'requiresApproval': json['requiresApproval'] == null ? undefined : json['requiresApproval'],
        'requiresPaidSubscription': json['requiresPaidSubscription'] == null ? undefined : json['requiresPaidSubscription'],
        'requiresLogin': json['requiresLogin'] == null ? undefined : json['requiresLogin'],
        'onboardingQuestions': json['onboardingQuestions'] == null ? undefined : ((json['onboardingQuestions'] as Array<any>).map(CommunityOnboardingQuestionFromJSON)),
        'bannedUsers': json['bannedUsers'] == null ? undefined : json['bannedUsers'],
    };
}

export function CommunityRulesToJSON(json: any): CommunityRules {
    return CommunityRulesToJSONTyped(json, false);
}

export function CommunityRulesToJSONTyped(value?: CommunityRules | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adminUserId': value['adminUserId'],
        'id': value['id'],
        'rules': value['rules'],
        'requiresApproval': value['requiresApproval'],
        'requiresPaidSubscription': value['requiresPaidSubscription'],
        'requiresLogin': value['requiresLogin'],
        'onboardingQuestions': value['onboardingQuestions'] == null ? undefined : ((value['onboardingQuestions'] as Array<any>).map(CommunityOnboardingQuestionToJSON)),
        'bannedUsers': value['bannedUsers'],
    };
}

