/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentMessage
 */
export interface CommentMessage {
    /**
     * 
     * @type {string}
     * @memberof CommentMessage
     */
    message: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommentMessage
     */
    mentions: Array<string>;
}

/**
 * Check if a given object implements the CommentMessage interface.
 */
export function instanceOfCommentMessage(value: object): value is CommentMessage {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('mentions' in value) || value['mentions'] === undefined) return false;
    return true;
}

export function CommentMessageFromJSON(json: any): CommentMessage {
    return CommentMessageFromJSONTyped(json, false);
}

export function CommentMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'mentions': json['mentions'],
    };
}

export function CommentMessageToJSON(json: any): CommentMessage {
    return CommentMessageToJSONTyped(json, false);
}

export function CommentMessageToJSONTyped(value?: CommentMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'mentions': value['mentions'],
    };
}

