/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CryptoWallets } from './CryptoWallets';
import {
    CryptoWalletsFromJSON,
    CryptoWalletsFromJSONTyped,
    CryptoWalletsToJSON,
    CryptoWalletsToJSONTyped,
} from './CryptoWallets';
import type { BankAccount1 } from './BankAccount1';
import {
    BankAccount1FromJSON,
    BankAccount1FromJSONTyped,
    BankAccount1ToJSON,
    BankAccount1ToJSONTyped,
} from './BankAccount1';

/**
 * 
 * @export
 * @interface CommunityPaymentInfo1
 */
export interface CommunityPaymentInfo1 {
    /**
     * The unique identifier for the funding destination.
     * @type {string}
     * @memberof CommunityPaymentInfo1
     */
    id?: string;
    /**
     * The unique identifier for the community.
     * @type {string}
     * @memberof CommunityPaymentInfo1
     */
    communityId: string;
    /**
     * The list of cryptocurrency wallets for the community.
     * @type {Array<CryptoWallets>}
     * @memberof CommunityPaymentInfo1
     */
    cryptoWallets?: Array<CryptoWallets>;
    /**
     * The list of bank accounts for the community.
     * @type {Array<BankAccount1>}
     * @memberof CommunityPaymentInfo1
     */
    bankAccounts?: Array<BankAccount1>;
}

/**
 * Check if a given object implements the CommunityPaymentInfo1 interface.
 */
export function instanceOfCommunityPaymentInfo1(value: object): value is CommunityPaymentInfo1 {
    if (!('communityId' in value) || value['communityId'] === undefined) return false;
    return true;
}

export function CommunityPaymentInfo1FromJSON(json: any): CommunityPaymentInfo1 {
    return CommunityPaymentInfo1FromJSONTyped(json, false);
}

export function CommunityPaymentInfo1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityPaymentInfo1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'communityId': json['communityId'],
        'cryptoWallets': json['cryptoWallets'] == null ? undefined : ((json['cryptoWallets'] as Array<any>).map(CryptoWalletsFromJSON)),
        'bankAccounts': json['bankAccounts'] == null ? undefined : ((json['bankAccounts'] as Array<any>).map(BankAccount1FromJSON)),
    };
}

export function CommunityPaymentInfo1ToJSON(json: any): CommunityPaymentInfo1 {
    return CommunityPaymentInfo1ToJSONTyped(json, false);
}

export function CommunityPaymentInfo1ToJSONTyped(value?: CommunityPaymentInfo1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'communityId': value['communityId'],
        'cryptoWallets': value['cryptoWallets'] == null ? undefined : ((value['cryptoWallets'] as Array<any>).map(CryptoWalletsToJSON)),
        'bankAccounts': value['bankAccounts'] == null ? undefined : ((value['bankAccounts'] as Array<any>).map(BankAccount1ToJSON)),
    };
}

