/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Like } from './Like';
import {
    LikeFromJSON,
    LikeFromJSONTyped,
    LikeToJSON,
    LikeToJSONTyped,
} from './Like';
import type { CommentMessage } from './CommentMessage';
import {
    CommentMessageFromJSON,
    CommentMessageFromJSONTyped,
    CommentMessageToJSON,
    CommentMessageToJSONTyped,
} from './CommentMessage';

/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    userId: string;
    /**
     * 
     * @type {CommentMessage}
     * @memberof Comment
     */
    message: CommentMessage;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    timestamp: Date;
    /**
     * 
     * @type {Array<Like>}
     * @memberof Comment
     */
    likes?: Array<Like>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Comment
     */
    comments?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    postReference?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    commentReference?: string;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'message': CommentMessageFromJSON(json['message']),
        'timestamp': (new Date(json['timestamp'])),
        'likes': json['likes'] == null ? undefined : ((json['likes'] as Array<any>).map(LikeFromJSON)),
        'comments': json['comments'] == null ? undefined : json['comments'],
        'postReference': json['postReference'] == null ? undefined : json['postReference'],
        'commentReference': json['commentReference'] == null ? undefined : json['commentReference'],
    };
}

export function CommentToJSON(json: any): Comment {
    return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'message': CommentMessageToJSON(value['message']),
        'timestamp': ((value['timestamp']).toISOString()),
        'likes': value['likes'] == null ? undefined : ((value['likes'] as Array<any>).map(LikeToJSON)),
        'comments': value['comments'],
        'postReference': value['postReference'],
        'commentReference': value['commentReference'],
    };
}

