/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityOnboardingQuestion
 */
export interface CommunityOnboardingQuestion {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityOnboardingQuestion
     */
    adminUserId?: string;
    /**
     * The date and time when the community was created.
     * @type {Date}
     * @memberof CommunityOnboardingQuestion
     */
    createdAt?: Date;
    /**
     * The unique identifier for the question.
     * @type {string}
     * @memberof CommunityOnboardingQuestion
     */
    id?: string;
    /**
     * The question text.
     * @type {string}
     * @memberof CommunityOnboardingQuestion
     */
    question: string;
    /**
     * The answer text.
     * @type {string}
     * @memberof CommunityOnboardingQuestion
     */
    answer: string;
    /**
     * The correct answer.
     * @type {string}
     * @memberof CommunityOnboardingQuestion
     */
    rightAnswer?: string;
    /**
     * Whether the question requires approval.
     * @type {boolean}
     * @memberof CommunityOnboardingQuestion
     */
    requiresReview?: boolean;
}

/**
 * Check if a given object implements the CommunityOnboardingQuestion interface.
 */
export function instanceOfCommunityOnboardingQuestion(value: object): value is CommunityOnboardingQuestion {
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function CommunityOnboardingQuestionFromJSON(json: any): CommunityOnboardingQuestion {
    return CommunityOnboardingQuestionFromJSONTyped(json, false);
}

export function CommunityOnboardingQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityOnboardingQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'adminUserId': json['adminUserId'] == null ? undefined : json['adminUserId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'question': json['question'],
        'answer': json['answer'],
        'rightAnswer': json['rightAnswer'] == null ? undefined : json['rightAnswer'],
        'requiresReview': json['requiresReview'] == null ? undefined : json['requiresReview'],
    };
}

export function CommunityOnboardingQuestionToJSON(json: any): CommunityOnboardingQuestion {
    return CommunityOnboardingQuestionToJSONTyped(json, false);
}

export function CommunityOnboardingQuestionToJSONTyped(value?: CommunityOnboardingQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adminUserId': value['adminUserId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'id': value['id'],
        'question': value['question'],
        'answer': value['answer'],
        'rightAnswer': value['rightAnswer'],
        'requiresReview': value['requiresReview'],
    };
}

