/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunityPaidContribution } from './CommunityPaidContribution';
import {
    CommunityPaidContributionFromJSON,
    CommunityPaidContributionFromJSONTyped,
    CommunityPaidContributionToJSON,
    CommunityPaidContributionToJSONTyped,
} from './CommunityPaidContribution';
import type { Sponsor } from './Sponsor';
import {
    SponsorFromJSON,
    SponsorFromJSONTyped,
    SponsorToJSON,
    SponsorToJSONTyped,
} from './Sponsor';
import type { CommunityGoals } from './CommunityGoals';
import {
    CommunityGoalsFromJSON,
    CommunityGoalsFromJSONTyped,
    CommunityGoalsToJSON,
    CommunityGoalsToJSONTyped,
} from './CommunityGoals';
import type { CommunitySurvey } from './CommunitySurvey';
import {
    CommunitySurveyFromJSON,
    CommunitySurveyFromJSONTyped,
    CommunitySurveyToJSON,
    CommunitySurveyToJSONTyped,
} from './CommunitySurvey';

/**
 * 
 * @export
 * @interface Community
 */
export interface Community {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof Community
     */
    adminUserId: string;
    /**
     * The unique identifier for the community.
     * @type {string}
     * @memberof Community
     */
    id: string;
    /**
     * The image of the community.
     * @type {string}
     * @memberof Community
     */
    image: string;
    /**
     * The slug of the community.
     * @type {string}
     * @memberof Community
     */
    slug: string;
    /**
     * The title of the community.
     * @type {string}
     * @memberof Community
     */
    title: string;
    /**
     * The description of the community.
     * @type {string}
     * @memberof Community
     */
    description?: string;
    /**
     * Whether the community is featured.
     * @type {boolean}
     * @memberof Community
     */
    featured?: boolean;
    /**
     * The interests of the community.
     * @type {Array<string>}
     * @memberof Community
     */
    interests?: Array<string>;
    /**
     * The members of the community.
     * @type {Array<string>}
     * @memberof Community
     */
    members?: Array<string>;
    /**
     * Whether the community is open to the public.
     * @type {boolean}
     * @memberof Community
     */
    requiresLogin?: boolean;
    /**
     * The invite list of the community.
     * @type {Array<string>}
     * @memberof Community
     */
    inviteList?: Array<string>;
    /**
     * The invite code of the community.
     * @type {string}
     * @memberof Community
     */
    inviteCode?: string;
    /**
     * The members requiring approval of the community.
     * @type {Array<string>}
     * @memberof Community
     */
    membersRequiringApproval?: Array<string>;
    /**
     * Whether the community requires manual approval.
     * @type {boolean}
     * @memberof Community
     */
    requiresManualApproval?: boolean;
    /**
     * Whether the community requires a paid subscription.
     * @type {boolean}
     * @memberof Community
     */
    requiresPaidSubscription?: boolean;
    /**
     * The type of meetings the community holds - virtual or in-person (IRL).
     * @type {string}
     * @memberof Community
     */
    meetingType?: CommunityMeetingTypeEnum;
    /**
     * The onboarding questions of the community.
     * @type {Array<string>}
     * @memberof Community
     */
    onboardingQuestions?: Array<string>;
    /**
     * 
     * @type {Array<CommunitySurvey>}
     * @memberof Community
     */
    communitySurvey?: Array<CommunitySurvey>;
    /**
     * The rules of the community.
     * @type {string}
     * @memberof Community
     */
    rules: string;
    /**
     * The date and time when the community was launched.
     * @type {Date}
     * @memberof Community
     */
    launchDateTime?: Date;
    /**
     * The status of the community.
     * @type {string}
     * @memberof Community
     */
    status?: CommunityStatusEnum;
    /**
     * The date and time when the community was created.
     * @type {Date}
     * @memberof Community
     */
    createdAt?: Date;
    /**
     * The date and time when the community was last modified.
     * @type {Date}
     * @memberof Community
     */
    modifiedAt?: Date;
    /**
     * The IPFS hash of the community.
     * @type {string}
     * @memberof Community
     */
    ipfsHash?: string;
    /**
     * Whether the user has never visited the community before.
     * @type {boolean}
     * @memberof Community
     */
    firstVisit?: boolean;
    /**
     * The donations made to the community.
     * @type {Array<CommunityPaidContribution>}
     * @memberof Community
     */
    communityPaidContributions?: Array<CommunityPaidContribution>;
    /**
     * The destination of the community funding.
     * @type {string}
     * @memberof Community
     */
    communityFundingDestination?: string;
    /**
     * The goals of the community.
     * @type {Array<CommunityGoals>}
     * @memberof Community
     */
    goals?: Array<CommunityGoals> | null;
    /**
     * The sponsors of the community.
     * @type {Array<Sponsor>}
     * @memberof Community
     */
    sponsors?: Array<Sponsor> | null;
}


/**
 * @export
 */
export const CommunityMeetingTypeEnum = {
    Virtual: 'VIRTUAL',
    Irl: 'IRL'
} as const;
export type CommunityMeetingTypeEnum = typeof CommunityMeetingTypeEnum[keyof typeof CommunityMeetingTypeEnum];

/**
 * @export
 */
export const CommunityStatusEnum = {
    Live: 'LIVE',
    Paused: 'PAUSED',
    PreLaunch: 'PRE_LAUNCH',
    Deleted: 'DELETED'
} as const;
export type CommunityStatusEnum = typeof CommunityStatusEnum[keyof typeof CommunityStatusEnum];


/**
 * Check if a given object implements the Community interface.
 */
export function instanceOfCommunity(value: object): value is Community {
    if (!('adminUserId' in value) || value['adminUserId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function CommunityFromJSON(json: any): Community {
    return CommunityFromJSONTyped(json, false);
}

export function CommunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Community {
    if (json == null) {
        return json;
    }
    return {
        
        'adminUserId': json['adminUserId'],
        'id': json['id'],
        'image': json['image'],
        'slug': json['slug'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'interests': json['interests'] == null ? undefined : json['interests'],
        'members': json['members'] == null ? undefined : json['members'],
        'requiresLogin': json['requiresLogin'] == null ? undefined : json['requiresLogin'],
        'inviteList': json['inviteList'] == null ? undefined : json['inviteList'],
        'inviteCode': json['inviteCode'] == null ? undefined : json['inviteCode'],
        'membersRequiringApproval': json['membersRequiringApproval'] == null ? undefined : json['membersRequiringApproval'],
        'requiresManualApproval': json['requiresManualApproval'] == null ? undefined : json['requiresManualApproval'],
        'requiresPaidSubscription': json['requiresPaidSubscription'] == null ? undefined : json['requiresPaidSubscription'],
        'meetingType': json['meetingType'] == null ? undefined : json['meetingType'],
        'onboardingQuestions': json['onboardingQuestions'] == null ? undefined : json['onboardingQuestions'],
        'communitySurvey': json['communitySurvey'] == null ? undefined : ((json['communitySurvey'] as Array<any>).map(CommunitySurveyFromJSON)),
        'rules': json['rules'],
        'launchDateTime': json['launchDateTime'] == null ? undefined : (new Date(json['launchDateTime'])),
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
        'ipfsHash': json['ipfsHash'] == null ? undefined : json['ipfsHash'],
        'firstVisit': json['firstVisit'] == null ? undefined : json['firstVisit'],
        'communityPaidContributions': json['communityPaidContributions'] == null ? undefined : ((json['communityPaidContributions'] as Array<any>).map(CommunityPaidContributionFromJSON)),
        'communityFundingDestination': json['communityFundingDestination'] == null ? undefined : json['communityFundingDestination'],
        'goals': json['goals'] == null ? undefined : ((json['goals'] as Array<any>).map(CommunityGoalsFromJSON)),
        'sponsors': json['sponsors'] == null ? undefined : ((json['sponsors'] as Array<any>).map(SponsorFromJSON)),
    };
}

export function CommunityToJSON(json: any): Community {
    return CommunityToJSONTyped(json, false);
}

export function CommunityToJSONTyped(value?: Community | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adminUserId': value['adminUserId'],
        'id': value['id'],
        'image': value['image'],
        'slug': value['slug'],
        'title': value['title'],
        'description': value['description'],
        'featured': value['featured'],
        'interests': value['interests'],
        'members': value['members'],
        'requiresLogin': value['requiresLogin'],
        'inviteList': value['inviteList'],
        'inviteCode': value['inviteCode'],
        'membersRequiringApproval': value['membersRequiringApproval'],
        'requiresManualApproval': value['requiresManualApproval'],
        'requiresPaidSubscription': value['requiresPaidSubscription'],
        'meetingType': value['meetingType'],
        'onboardingQuestions': value['onboardingQuestions'],
        'communitySurvey': value['communitySurvey'] == null ? undefined : ((value['communitySurvey'] as Array<any>).map(CommunitySurveyToJSON)),
        'rules': value['rules'],
        'launchDateTime': value['launchDateTime'] == null ? undefined : ((value['launchDateTime']).toISOString()),
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
        'ipfsHash': value['ipfsHash'],
        'firstVisit': value['firstVisit'],
        'communityPaidContributions': value['communityPaidContributions'] == null ? undefined : ((value['communityPaidContributions'] as Array<any>).map(CommunityPaidContributionToJSON)),
        'communityFundingDestination': value['communityFundingDestination'],
        'goals': value['goals'] == null ? undefined : ((value['goals'] as Array<any>).map(CommunityGoalsToJSON)),
        'sponsors': value['sponsors'] == null ? undefined : ((value['sponsors'] as Array<any>).map(SponsorToJSON)),
    };
}

