/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunitySurvey
 */
export interface CommunitySurvey {
    /**
     * The unique identifier for the survey.
     * @type {string}
     * @memberof CommunitySurvey
     */
    id: string;
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunitySurvey
     */
    question: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommunitySurvey
     */
    options: Array<string>;
}

/**
 * Check if a given object implements the CommunitySurvey interface.
 */
export function instanceOfCommunitySurvey(value: object): value is CommunitySurvey {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function CommunitySurveyFromJSON(json: any): CommunitySurvey {
    return CommunitySurveyFromJSONTyped(json, false);
}

export function CommunitySurveyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunitySurvey {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'question': json['question'],
        'options': json['options'],
    };
}

export function CommunitySurveyToJSON(json: any): CommunitySurvey {
    return CommunitySurveyToJSONTyped(json, false);
}

export function CommunitySurveyToJSONTyped(value?: CommunitySurvey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'question': value['question'],
        'options': value['options'],
    };
}

