/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityMembership
 */
export interface CommunityMembership {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityMembership
     */
    communityId: string;
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityMembership
     */
    member: string;
    /**
     * The unique identifier for the user.
     * @type {boolean}
     * @memberof CommunityMembership
     */
    paidMember: boolean;
    /**
     * The unique identifier for the user.
     * @type {boolean}
     * @memberof CommunityMembership
     */
    admin: boolean;
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityMembership
     */
    membershipStatus: CommunityMembershipMembershipStatusEnum;
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityMembership
     */
    userId: string;
}


/**
 * @export
 */
export const CommunityMembershipMembershipStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Removed: 'REMOVED'
} as const;
export type CommunityMembershipMembershipStatusEnum = typeof CommunityMembershipMembershipStatusEnum[keyof typeof CommunityMembershipMembershipStatusEnum];


/**
 * Check if a given object implements the CommunityMembership interface.
 */
export function instanceOfCommunityMembership(value: object): value is CommunityMembership {
    if (!('communityId' in value) || value['communityId'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    if (!('paidMember' in value) || value['paidMember'] === undefined) return false;
    if (!('admin' in value) || value['admin'] === undefined) return false;
    if (!('membershipStatus' in value) || value['membershipStatus'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CommunityMembershipFromJSON(json: any): CommunityMembership {
    return CommunityMembershipFromJSONTyped(json, false);
}

export function CommunityMembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityMembership {
    if (json == null) {
        return json;
    }
    return {
        
        'communityId': json['communityId'],
        'member': json['member'],
        'paidMember': json['paidMember'],
        'admin': json['admin'],
        'membershipStatus': json['membershipStatus'],
        'userId': json['userId'],
    };
}

export function CommunityMembershipToJSON(json: any): CommunityMembership {
    return CommunityMembershipToJSONTyped(json, false);
}

export function CommunityMembershipToJSONTyped(value?: CommunityMembership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'communityId': value['communityId'],
        'member': value['member'],
        'paidMember': value['paidMember'],
        'admin': value['admin'],
        'membershipStatus': value['membershipStatus'],
        'userId': value['userId'],
    };
}

