/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityPaidContribution
 */
export interface CommunityPaidContribution {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    userId: string;
    /**
     * The unique identifier for the community.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    communityId: string;
    /**
     * The unique identifier for the post.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    postId?: string;
    /**
     * The amount paid by the user.
     * @type {number}
     * @memberof CommunityPaidContribution
     */
    amount: number;
    /**
     * The date of the payment.
     * @type {Date}
     * @memberof CommunityPaidContribution
     */
    date: Date;
    /**
     * A note or message associated with the payment.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    note?: string;
    /**
     * The status of the payment.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    status: CommunityPaidContributionStatusEnum;
    /**
     * The unique identifier for the transaction.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    transactionId: string;
    /**
     * The method used for payment.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    paymentMethod: CommunityPaidContributionPaymentMethodEnum;
    /**
     * The cryptocurrency used for payment.
     * @type {string}
     * @memberof CommunityPaidContribution
     */
    cryptoCurrency?: CommunityPaidContributionCryptoCurrencyEnum;
}


/**
 * @export
 */
export const CommunityPaidContributionStatusEnum = {
    Pending: 'PENDING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Refunded: 'REFUNDED'
} as const;
export type CommunityPaidContributionStatusEnum = typeof CommunityPaidContributionStatusEnum[keyof typeof CommunityPaidContributionStatusEnum];

/**
 * @export
 */
export const CommunityPaidContributionPaymentMethodEnum = {
    CreditCard: 'CREDIT_CARD',
    DebitCard: 'DEBIT_CARD',
    Paypal: 'PAYPAL',
    Venmo: 'VENMO',
    Cryptocurrency: 'CRYPTOCURRENCY',
    Oinks: 'OINKS'
} as const;
export type CommunityPaidContributionPaymentMethodEnum = typeof CommunityPaidContributionPaymentMethodEnum[keyof typeof CommunityPaidContributionPaymentMethodEnum];

/**
 * @export
 */
export const CommunityPaidContributionCryptoCurrencyEnum = {
    Bitcoin: 'BITCOIN',
    Ethereum: 'ETHEREUM',
    Solana: 'SOLANA',
    Base: 'BASE'
} as const;
export type CommunityPaidContributionCryptoCurrencyEnum = typeof CommunityPaidContributionCryptoCurrencyEnum[keyof typeof CommunityPaidContributionCryptoCurrencyEnum];


/**
 * Check if a given object implements the CommunityPaidContribution interface.
 */
export function instanceOfCommunityPaidContribution(value: object): value is CommunityPaidContribution {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('communityId' in value) || value['communityId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function CommunityPaidContributionFromJSON(json: any): CommunityPaidContribution {
    return CommunityPaidContributionFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to a `CommunityPaidContribution` instance, mapping all required and optional fields.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - If true, discriminator properties are ignored (not used in this function)
 * @returns A `CommunityPaidContribution` object with properties parsed from the input JSON
 */
export function CommunityPaidContributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityPaidContribution {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'communityId': json['communityId'],
        'postId': json['postId'] == null ? undefined : json['postId'],
        'amount': json['amount'],
        'date': (new Date(json['date'])),
        'note': json['note'] == null ? undefined : json['note'],
        'status': json['status'],
        'transactionId': json['transactionId'],
        'paymentMethod': json['paymentMethod'],
        'cryptoCurrency': json['cryptoCurrency'] == null ? undefined : json['cryptoCurrency'],
    };
}

export function CommunityPaidContributionToJSON(json: any): CommunityPaidContribution {
    return CommunityPaidContributionToJSONTyped(json, false);
}

/**
 * Converts a `CommunityPaidContribution` object to a JSON-compatible representation.
 *
 * Serializes the `date` property to an ISO string and includes all properties, preserving optional fields as-is.
 *
 * @param value - The `CommunityPaidContribution` object to serialize, or `null`/`undefined`
 * @returns A JSON-compatible object representing the contribution, or `null`/`undefined` if input is `null`/`undefined`
 */
export function CommunityPaidContributionToJSONTyped(value?: CommunityPaidContribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'communityId': value['communityId'],
        'postId': value['postId'],
        'amount': value['amount'],
        'date': ((value['date']).toISOString()),
        'note': value['note'],
        'status': value['status'],
        'transactionId': value['transactionId'],
        'paymentMethod': value['paymentMethod'],
        'cryptoCurrency': value['cryptoCurrency'],
    };
}

