/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoWallet
 */
export interface CryptoWallet {
    /**
     * The cryptocurrency wallet address.
     * @type {string}
     * @memberof CryptoWallet
     */
    walletAddress: string;
    /**
     * The second cryptocurrency wallet address.
     * @type {string}
     * @memberof CryptoWallet
     */
    walletAddress2?: string;
    /**
     * The type of cryptocurrency.
     * @type {string}
     * @memberof CryptoWallet
     */
    cryptoCurrency: CryptoWalletCryptoCurrencyEnum;
    /**
     * A note or comment about the wallet.
     * @type {string}
     * @memberof CryptoWallet
     */
    note?: string;
}


/**
 * @export
 */
export const CryptoWalletCryptoCurrencyEnum = {
    Bitcoin: 'BITCOIN',
    Ethereum: 'ETHEREUM',
    Solana: 'SOLANA',
    Base: 'BASE'
} as const;
export type CryptoWalletCryptoCurrencyEnum = typeof CryptoWalletCryptoCurrencyEnum[keyof typeof CryptoWalletCryptoCurrencyEnum];


/**
 * Check if a given object implements the CryptoWallet interface.
 */
export function instanceOfCryptoWallet(value: object): value is CryptoWallet {
    if (!('walletAddress' in value) || value['walletAddress'] === undefined) return false;
    if (!('cryptoCurrency' in value) || value['cryptoCurrency'] === undefined) return false;
    return true;
}

export function CryptoWalletFromJSON(json: any): CryptoWallet {
    return CryptoWalletFromJSONTyped(json, false);
}

export function CryptoWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoWallet {
    if (json == null) {
        return json;
    }
    return {
        
        'walletAddress': json['walletAddress'],
        'walletAddress2': json['walletAddress2'] == null ? undefined : json['walletAddress2'],
        'cryptoCurrency': json['cryptoCurrency'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CryptoWalletToJSON(json: any): CryptoWallet {
    return CryptoWalletToJSONTyped(json, false);
}

export function CryptoWalletToJSONTyped(value?: CryptoWallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'walletAddress': value['walletAddress'],
        'walletAddress2': value['walletAddress2'],
        'cryptoCurrency': value['cryptoCurrency'],
        'note': value['note'],
    };
}

