/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoPricing
 */
export interface CryptoPricing {
    /**
     * 
     * @type {Array<string>}
     * @memberof CryptoPricing
     */
    cryptos?: Array<CryptoPricingCryptosEnum>;
    /**
     * The fiat currency to convert the prices to.
     * @type {string}
     * @memberof CryptoPricing
     */
    fiat?: CryptoPricingFiatEnum;
}


/**
 * @export
 */
export const CryptoPricingCryptosEnum = {
    Ethereum: 'ethereum',
    Solana: 'solana',
    Bitcoin: 'bitcoin',
    Base: 'base'
} as const;
export type CryptoPricingCryptosEnum = typeof CryptoPricingCryptosEnum[keyof typeof CryptoPricingCryptosEnum];

/**
 * @export
 */
export const CryptoPricingFiatEnum = {
    Usd: 'usd',
    Eur: 'eur',
    Gbp: 'gbp',
    Jpy: 'jpy',
    Aud: 'aud',
    Cad: 'cad',
    Chf: 'chf',
    Cny: 'cny',
    Sek: 'sek',
    Nzd: 'nzd'
} as const;
export type CryptoPricingFiatEnum = typeof CryptoPricingFiatEnum[keyof typeof CryptoPricingFiatEnum];


/**
 * Check if a given object implements the CryptoPricing interface.
 */
export function instanceOfCryptoPricing(value: object): value is CryptoPricing {
    return true;
}

export function CryptoPricingFromJSON(json: any): CryptoPricing {
    return CryptoPricingFromJSONTyped(json, false);
}

export function CryptoPricingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoPricing {
    if (json == null) {
        return json;
    }
    return {
        
        'cryptos': json['cryptos'] == null ? undefined : json['cryptos'],
        'fiat': json['fiat'] == null ? undefined : json['fiat'],
    };
}

export function CryptoPricingToJSON(json: any): CryptoPricing {
    return CryptoPricingToJSONTyped(json, false);
}

export function CryptoPricingToJSONTyped(value?: CryptoPricing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cryptos': value['cryptos'],
        'fiat': value['fiat'],
    };
}

