/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoWallets
 */
export interface CryptoWallets {
    /**
     * The cryptocurrency wallet address.
     * @type {string}
     * @memberof CryptoWallets
     */
    walletAddress: string;
    /**
     * The second cryptocurrency wallet address.
     * @type {string}
     * @memberof CryptoWallets
     */
    walletAddress2?: string;
    /**
     * The type of cryptocurrency.
     * @type {string}
     * @memberof CryptoWallets
     */
    cryptoCurrency: CryptoWalletsCryptoCurrencyEnum;
    /**
     * A note or comment about the wallet.
     * @type {string}
     * @memberof CryptoWallets
     */
    note?: string;
}


/**
 * @export
 */
export const CryptoWalletsCryptoCurrencyEnum = {
    Bitcoin: 'BITCOIN',
    Ethereum: 'ETHEREUM',
    Solana: 'SOLANA',
    Base: 'BASE'
} as const;
export type CryptoWalletsCryptoCurrencyEnum = typeof CryptoWalletsCryptoCurrencyEnum[keyof typeof CryptoWalletsCryptoCurrencyEnum];


/**
 * Check if a given object implements the CryptoWallets interface.
 */
export function instanceOfCryptoWallets(value: object): value is CryptoWallets {
    if (!('walletAddress' in value) || value['walletAddress'] === undefined) return false;
    if (!('cryptoCurrency' in value) || value['cryptoCurrency'] === undefined) return false;
    return true;
}

export function CryptoWalletsFromJSON(json: any): CryptoWallets {
    return CryptoWalletsFromJSONTyped(json, false);
}

export function CryptoWalletsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoWallets {
    if (json == null) {
        return json;
    }
    return {
        
        'walletAddress': json['walletAddress'],
        'walletAddress2': json['walletAddress2'] == null ? undefined : json['walletAddress2'],
        'cryptoCurrency': json['cryptoCurrency'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CryptoWalletsToJSON(json: any): CryptoWallets {
    return CryptoWalletsToJSONTyped(json, false);
}

export function CryptoWalletsToJSONTyped(value?: CryptoWallets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'walletAddress': value['walletAddress'],
        'walletAddress2': value['walletAddress2'],
        'cryptoCurrency': value['cryptoCurrency'],
        'note': value['note'],
    };
}

