/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Amount } from './Amount';
import {
    AmountFromJSON,
    AmountFromJSONTyped,
    AmountToJSON,
    AmountToJSONTyped,
} from './Amount';

/**
 * 
 * @export
 * @interface Donation
 */
export interface Donation {
    /**
     * 
     * @type {string}
     * @memberof Donation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Donation
     */
    eventSlotId?: string;
    /**
     * 
     * @type {Amount}
     * @memberof Donation
     */
    amount?: Amount;
    /**
     * 
     * @type {string}
     * @memberof Donation
     */
    sponsorId?: string;
}

/**
 * Type guard that always treats any object as a `Donation`.
 *
 * This function does not perform any runtime checks and always returns `true`.
 */
export function instanceOfDonation(value: object): value is Donation {
    return true;
}

/**
 * Converts a JSON object into a `Donation` instance.
 *
 * Delegates to `DonationFromJSONTyped` with discriminator checks enabled.
 *
 * @returns The corresponding `Donation` object.
 */
export function DonationFromJSON(json: any): Donation {
    return DonationFromJSONTyped(json, false);
}

/**
 * Converts a JSON object into a `Donation` instance, mapping each property and converting the `amount` field using `AmountFromJSON`.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - If true, discriminator properties are ignored during conversion
 * @returns The resulting `Donation` instance, or `null` if the input is `null`
 */
export function DonationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Donation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'amount': json['amount'] == null ? undefined : AmountFromJSON(json['amount']),
        'sponsorId': json['sponsorId'] == null ? undefined : json['sponsorId'],
    };
}

/**
 * Converts a JSON object to a `Donation` instance.
 *
 * Delegates to `DonationToJSONTyped` with discriminator checks enabled.
 * @returns The resulting `Donation` object.
 */
export function DonationToJSON(json: any): Donation {
    return DonationToJSONTyped(json, false);
}

/**
 * Converts a `Donation` object to a JSON representation.
 *
 * @param value - The `Donation` object to convert, or `null`/`undefined`
 * @param ignoreDiscriminator - If true, discriminator properties are ignored (not used in this implementation)
 * @returns The JSON object representing the `Donation`, or the input if it is `null` or `undefined`
 */
export function DonationToJSONTyped(value?: Donation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventSlotId': value['eventSlotId'],
        'amount': AmountToJSON(value['amount']),
        'sponsorId': value['sponsorId'],
    };
}

