/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventType = {
    PreRecorded: 'PRE_RECORDED',
    InPerson: 'IN_PERSON',
    LiveStream: 'LIVE_STREAM'
} as const;
export type EventType = typeof EventType[keyof typeof EventType];


/**
 * Determines whether a given value is a valid EventType.
 *
 * @param value - The value to check for EventType membership
 * @returns True if the value matches one of the defined EventType values; otherwise, false
 */
export function instanceOfEventType(value: any): boolean {
    for (const key in EventType) {
        if (Object.prototype.hasOwnProperty.call(EventType, key)) {
            if (EventType[key as keyof typeof EventType] === value) {
                return true;
            }
        }
    }
    return false;
}

/**
 * Converts a JSON value to an `EventType`.
 *
 * @returns The corresponding `EventType` value.
 */
export function EventTypeFromJSON(json: any): EventType {
    return EventTypeFromJSONTyped(json, false);
}

/**
 * Converts a JSON value to an `EventType` without validation or transformation.
 *
 * @param json - The input value to convert
 * @param ignoreDiscriminator - Unused parameter included for compatibility with code generation patterns
 * @returns The input value cast as an `EventType`
 */
export function EventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventType {
    return json as EventType;
}

/**
 * Converts an `EventType` value to a JSON-compatible format.
 *
 * @returns The input `EventType` value as a JSON-serializable value, or `null` if input is `null` or `undefined`.
 */
export function EventTypeToJSON(value?: EventType | null): any {
    return value as any;
}

/**
 * Converts a value to the `EventType` type without validation or transformation.
 *
 * @param value - The value to cast to `EventType`
 * @param ignoreDiscriminator - Unused parameter included for compatibility with code generation patterns
 * @returns The input value cast as an `EventType`
 */
export function EventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EventType {
    return value as EventType;
}

