/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventPrivacy = {
    Public: 'PUBLIC',
    InviteOnly: 'INVITE_ONLY',
    PaidMembers: 'PAID_MEMBERS'
} as const;
export type EventPrivacy = typeof EventPrivacy[keyof typeof EventPrivacy];


export function instanceOfEventPrivacy(value: any): boolean {
    for (const key in EventPrivacy) {
        if (Object.prototype.hasOwnProperty.call(EventPrivacy, key)) {
            if (EventPrivacy[key as keyof typeof EventPrivacy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventPrivacyFromJSON(json: any): EventPrivacy {
    return EventPrivacyFromJSONTyped(json, false);
}

export function EventPrivacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPrivacy {
    return json as EventPrivacy;
}

export function EventPrivacyToJSON(value?: EventPrivacy | null): any {
    return value as any;
}

export function EventPrivacyToJSONTyped(value: any, ignoreDiscriminator: boolean): EventPrivacy {
    return value as EventPrivacy;
}

