/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Address } from './Address';
import {
    instanceOfAddress,
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './Address';

/**
 * @type EventSlotAddress
 * 
 * @export
 */
export type EventSlotAddress = Address | string;

export function EventSlotAddressFromJSON(json: any): EventSlotAddress {
    return EventSlotAddressFromJSONTyped(json, false);
}

export function EventSlotAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSlotAddress {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAddress(json)) {
        return AddressFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EventSlotAddressToJSON(json: any): any {
    return EventSlotAddressToJSONTyped(json, false);
}

export function EventSlotAddressToJSONTyped(value?: EventSlotAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAddress(value)) {
        return AddressToJSON(value as Address);
    }

    return {};
}

