/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ticket } from './Ticket';
import {
    TicketFromJSON,
    TicketFromJSONTyped,
    TicketToJSON,
    TicketToJSONTyped,
} from './Ticket';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { PromoCode } from './PromoCode';
import {
    PromoCodeFromJSON,
    PromoCodeFromJSONTyped,
    PromoCodeToJSON,
    PromoCodeToJSONTyped,
} from './PromoCode';
import type { Donation } from './Donation';
import {
    DonationFromJSON,
    DonationFromJSONTyped,
    DonationToJSON,
    DonationToJSONTyped,
} from './Donation';
import type { TicketOptions } from './TicketOptions';
import {
    TicketOptionsFromJSON,
    TicketOptionsFromJSONTyped,
    TicketOptionsToJSON,
    TicketOptionsToJSONTyped,
} from './TicketOptions';
import type { EventSponsor } from './EventSponsor';
import {
    EventSponsorFromJSON,
    EventSponsorFromJSONTyped,
    EventSponsorToJSON,
    EventSponsorToJSONTyped,
} from './EventSponsor';
import type { Host } from './Host';
import {
    HostFromJSON,
    HostFromJSONTyped,
    HostToJSON,
    HostToJSONTyped,
} from './Host';

/**
 * 
 * @export
 * @interface EventSlot
 */
export interface EventSlot {
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof EventSlot
     */
    startTimeDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventSlot
     */
    endTimeDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    eventSlotStatus?: EventSlotEventSlotStatusEnum;
    /**
     * 
     * @type {Array<PromoCode>}
     * @memberof EventSlot
     */
    promoCodes?: Array<PromoCode>;
    /**
     * 
     * @type {number}
     * @memberof EventSlot
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    currency?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EventSlot
     */
    cryptoAccepted?: boolean;
    /**
     * 
     * @type {Array<EventSponsor>}
     * @memberof EventSlot
     */
    sponsors?: Array<EventSponsor>;
    /**
     * 
     * @type {boolean}
     * @memberof EventSlot
     */
    locationNeeded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EventSlot
     */
    locationPartnership?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EventSlot
     */
    fundsNeeded?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EventSlot
     */
    fundGoal?: number;
    /**
     * 
     * @type {Address}
     * @memberof EventSlot
     */
    address?: Address;
    /**
     * 
     * @type {Array<Donation>}
     * @memberof EventSlot
     */
    donations?: Array<Donation>;
    /**
     * 
     * @type {Array<Ticket>}
     * @memberof EventSlot
     */
    tickets?: Array<Ticket>;
    /**
     * 
     * @type {Array<Host>}
     * @memberof EventSlot
     */
    hosts?: Array<Host>;
    /**
     * 
     * @type {Array<TicketOptions>}
     * @memberof EventSlot
     */
    ticketOptions?: Array<TicketOptions>;
}


/**
 * @export
 */
export const EventSlotEventSlotStatusEnum = {
    Available: 'AVAILABLE',
    SoldOut: 'SOLD_OUT',
    Expired: 'EXPIRED'
} as const;
export type EventSlotEventSlotStatusEnum = typeof EventSlotEventSlotStatusEnum[keyof typeof EventSlotEventSlotStatusEnum];


/**
 * Check if a given object implements the EventSlot interface.
 */
export function instanceOfEventSlot(value: object): value is EventSlot {
    return true;
}

export function EventSlotFromJSON(json: any): EventSlot {
    return EventSlotFromJSONTyped(json, false);
}

export function EventSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSlot {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'startTimeDate': json['startTimeDate'] == null ? undefined : (new Date(json['startTimeDate'])),
        'endTimeDate': json['endTimeDate'] == null ? undefined : (new Date(json['endTimeDate'])),
        'eventSlotStatus': json['eventSlotStatus'] == null ? undefined : json['eventSlotStatus'],
        'promoCodes': json['promoCodes'] == null ? undefined : ((json['promoCodes'] as Array<any>).map(PromoCodeFromJSON)),
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'cryptoAccepted': json['cryptoAccepted'] == null ? undefined : json['cryptoAccepted'],
        'sponsors': json['sponsors'] == null ? undefined : ((json['sponsors'] as Array<any>).map(EventSponsorFromJSON)),
        'locationNeeded': json['locationNeeded'] == null ? undefined : json['locationNeeded'],
        'locationPartnership': json['locationPartnership'] == null ? undefined : json['locationPartnership'],
        'fundsNeeded': json['fundsNeeded'] == null ? undefined : json['fundsNeeded'],
        'fundGoal': json['fundGoal'] == null ? undefined : json['fundGoal'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'donations': json['donations'] == null ? undefined : ((json['donations'] as Array<any>).map(DonationFromJSON)),
        'tickets': json['tickets'] == null ? undefined : ((json['tickets'] as Array<any>).map(TicketFromJSON)),
        'hosts': json['hosts'] == null ? undefined : ((json['hosts'] as Array<any>).map(HostFromJSON)),
        'ticketOptions': json['ticketOptions'] == null ? undefined : ((json['ticketOptions'] as Array<any>).map(TicketOptionsFromJSON)),
    };
}

export function EventSlotToJSON(json: any): EventSlot {
    return EventSlotToJSONTyped(json, false);
}

export function EventSlotToJSONTyped(value?: EventSlot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventId': value['eventId'],
        'title': value['title'],
        'description': value['description'],
        'startTimeDate': value['startTimeDate'] == null ? undefined : ((value['startTimeDate']).toISOString()),
        'endTimeDate': value['endTimeDate'] == null ? undefined : ((value['endTimeDate']).toISOString()),
        'eventSlotStatus': value['eventSlotStatus'],
        'promoCodes': value['promoCodes'] == null ? undefined : ((value['promoCodes'] as Array<any>).map(PromoCodeToJSON)),
        'price': value['price'],
        'currency': value['currency'],
        'cryptoAccepted': value['cryptoAccepted'],
        'sponsors': value['sponsors'] == null ? undefined : ((value['sponsors'] as Array<any>).map(EventSponsorToJSON)),
        'locationNeeded': value['locationNeeded'],
        'locationPartnership': value['locationPartnership'],
        'fundsNeeded': value['fundsNeeded'],
        'fundGoal': value['fundGoal'],
        'address': AddressToJSON(value['address']),
        'donations': value['donations'] == null ? undefined : ((value['donations'] as Array<any>).map(DonationToJSON)),
        'tickets': value['tickets'] == null ? undefined : ((value['tickets'] as Array<any>).map(TicketToJSON)),
        'hosts': value['hosts'] == null ? undefined : ((value['hosts'] as Array<any>).map(HostToJSON)),
        'ticketOptions': value['ticketOptions'] == null ? undefined : ((value['ticketOptions'] as Array<any>).map(TicketOptionsToJSON)),
    };
}

