/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventSponsorImage } from './EventSponsorImage';
import {
    EventSponsorImageFromJSON,
    EventSponsorImageFromJSONTyped,
    EventSponsorImageToJSON,
    EventSponsorImageToJSONTyped,
} from './EventSponsorImage';

/**
 * 
 * @export
 * @interface EventSponsor
 */
export interface EventSponsor {
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    description?: string;
    /**
     * 
     * @type {EventSponsorImage}
     * @memberof EventSponsor
     */
    image?: EventSponsorImage;
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    link?: string;
}

/**
 * Check if a given object implements the EventSponsor interface.
 */
export function instanceOfEventSponsor(value: object): value is EventSponsor {
    return true;
}

export function EventSponsorFromJSON(json: any): EventSponsor {
    return EventSponsorFromJSONTyped(json, false);
}

export function EventSponsorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSponsor {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : EventSponsorImageFromJSON(json['image']),
        'link': json['link'] == null ? undefined : json['link'],
    };
}

export function EventSponsorToJSON(json: any): EventSponsor {
    return EventSponsorToJSONTyped(json, false);
}

export function EventSponsorToJSONTyped(value?: EventSponsor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSlotId': value['eventSlotId'],
        'title': value['title'],
        'description': value['description'],
        'image': EventSponsorImageToJSON(value['image']),
        'link': value['link'],
    };
}

