/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventSponsor
 */
export interface EventSponsor {
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EventSponsor
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventSponsor
     */
    images?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventSponsor
     */
    links?: Array<string>;
}

/**
 * Determines if the provided object is considered an `EventSponsor`.
 *
 * Always returns `true`, so any object will be treated as an `EventSponsor` regardless of its structure.
 */
export function instanceOfEventSponsor(value: object): value is EventSponsor {
    return true;
}

/**
 * Converts a JSON object to an `EventSponsor` instance.
 *
 * @returns An `EventSponsor` object created from the provided JSON data.
 */
export function EventSponsorFromJSON(json: any): EventSponsor {
    return EventSponsorFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to an `EventSponsor` instance, mapping missing or null properties to `undefined`.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - If true, skips discriminator property checks (not used in this implementation)
 * @returns An `EventSponsor` instance with properties populated from the JSON object
 */
export function EventSponsorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventSponsor {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'images': json['images'] == null ? undefined : json['images'],
        'links': json['links'] == null ? undefined : json['links'],
    };
}

/**
 * Converts a JSON object to an `EventSponsor` instance.
 *
 * @returns The corresponding `EventSponsor` object.
 */
export function EventSponsorToJSON(json: any): EventSponsor {
    return EventSponsorToJSONTyped(json, false);
}

/**
 * Converts an `EventSponsor` instance to a JSON object.
 *
 * If the input is `null` or `undefined`, returns it as is. Otherwise, constructs a JSON object with the corresponding `EventSponsor` properties.
 *
 * @param value - The `EventSponsor` instance to convert
 * @param ignoreDiscriminator - Ignored in this implementation
 * @returns A JSON object representing the `EventSponsor`, or `null`/`undefined` if the input is `null`/`undefined`
 */
export function EventSponsorToJSONTyped(value?: EventSponsor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSlotId': value['eventSlotId'],
        'title': value['title'],
        'description': value['description'],
        'images': value['images'],
        'links': value['links'],
    };
}

