/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventPrivacy } from './EventPrivacy';
import {
    EventPrivacyFromJSON,
    EventPrivacyFromJSONTyped,
    EventPrivacyToJSON,
    EventPrivacyToJSONTyped,
} from './EventPrivacy';
import type { EventRecurrence } from './EventRecurrence';
import {
    EventRecurrenceFromJSON,
    EventRecurrenceFromJSONTyped,
    EventRecurrenceToJSON,
    EventRecurrenceToJSONTyped,
} from './EventRecurrence';
import type { EventType } from './EventType';
import {
    EventTypeFromJSON,
    EventTypeFromJSONTyped,
    EventTypeToJSON,
    EventTypeToJSONTyped,
} from './EventType';
import type { EventSlot } from './EventSlot';
import {
    EventSlotFromJSON,
    EventSlotFromJSONTyped,
    EventSlotToJSON,
    EventSlotToJSONTyped,
} from './EventSlot';
import type { Sponsor } from './Sponsor';
import {
    SponsorFromJSON,
    SponsorFromJSONTyped,
    SponsorToJSON,
    SponsorToJSONTyped,
} from './Sponsor';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Event
     */
    images?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    timezone?: string;
    /**
     * 
     * @type {EventRecurrence}
     * @memberof Event
     */
    recurrence?: EventRecurrence;
    /**
     * 
     * @type {EventType}
     * @memberof Event
     */
    eventType?: EventType;
    /**
     * 
     * @type {EventPrivacy}
     * @memberof Event
     */
    eventPrivacy?: EventPrivacy;
    /**
     * 
     * @type {Array<Sponsor>}
     * @memberof Event
     */
    sponsors?: Array<Sponsor>;
    /**
     * 
     * @type {boolean}
     * @memberof Event
     */
    commentsEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    lumaWidget?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    redirectLink?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Event
     */
    questions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Event
     */
    links?: Array<string>;
    /**
     * 
     * @type {Array<EventSlot>}
     * @memberof Event
     */
    eventSlots?: Array<EventSlot>;
    /**
     * Indicates if all event slots have the same details
     * @type {boolean}
     * @memberof Event
     */
    sameSlotDetails?: boolean;
}



/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'images': json['images'] == null ? undefined : json['images'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'recurrence': json['recurrence'] == null ? undefined : EventRecurrenceFromJSON(json['recurrence']),
        'eventType': json['eventType'] == null ? undefined : EventTypeFromJSON(json['eventType']),
        'eventPrivacy': json['eventPrivacy'] == null ? undefined : EventPrivacyFromJSON(json['eventPrivacy']),
        'sponsors': json['sponsors'] == null ? undefined : ((json['sponsors'] as Array<any>).map(SponsorFromJSON)),
        'commentsEnabled': json['commentsEnabled'] == null ? undefined : json['commentsEnabled'],
        'lumaWidget': json['lumaWidget'] == null ? undefined : json['lumaWidget'],
        'redirectLink': json['redirectLink'] == null ? undefined : json['redirectLink'],
        'questions': json['questions'] == null ? undefined : json['questions'],
        'links': json['links'] == null ? undefined : json['links'],
        'eventSlots': json['eventSlots'] == null ? undefined : ((json['eventSlots'] as Array<any>).map(EventSlotFromJSON)),
        'sameSlotDetails': json['sameSlotDetails'] == null ? undefined : json['sameSlotDetails'],
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'images': value['images'],
        'timezone': value['timezone'],
        'recurrence': EventRecurrenceToJSON(value['recurrence']),
        'eventType': EventTypeToJSON(value['eventType']),
        'eventPrivacy': EventPrivacyToJSON(value['eventPrivacy']),
        'sponsors': value['sponsors'] == null ? undefined : ((value['sponsors'] as Array<any>).map(SponsorToJSON)),
        'commentsEnabled': value['commentsEnabled'],
        'lumaWidget': value['lumaWidget'],
        'redirectLink': value['redirectLink'],
        'questions': value['questions'],
        'links': value['links'],
        'eventSlots': value['eventSlots'] == null ? undefined : ((value['eventSlots'] as Array<any>).map(EventSlotToJSON)),
        'sameSlotDetails': value['sameSlotDetails'],
    };
}

