/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventType = {
    PreRecorded: 'PRE_RECORDED',
    InPerson: 'IN_PERSON',
    LiveStream: 'LIVE_STREAM'
} as const;
export type EventType = typeof EventType[keyof typeof EventType];


export function instanceOfEventType(value: any): boolean {
    for (const key in EventType) {
        if (Object.prototype.hasOwnProperty.call(EventType, key)) {
            if (EventType[key as keyof typeof EventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventTypeFromJSON(json: any): EventType {
    return EventTypeFromJSONTyped(json, false);
}

export function EventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventType {
    return json as EventType;
}

export function EventTypeToJSON(value?: EventType | null): any {
    return value as any;
}

export function EventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EventType {
    return value as EventType;
}

