/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventPrivacy = {
    Public: 'PUBLIC',
    InviteOnly: 'INVITE_ONLY',
    PaidMembers: 'PAID_MEMBERS'
} as const;
export type EventPrivacy = typeof EventPrivacy[keyof typeof EventPrivacy];


/**
 * Determines whether a given value is a valid `EventPrivacy` enum value.
 *
 * @param value - The value to check for membership in the `EventPrivacy` enum
 * @returns `true` if the value matches one of the defined `EventPrivacy` values; otherwise, `false`
 */
export function instanceOfEventPrivacy(value: any): boolean {
    for (const key in EventPrivacy) {
        if (Object.prototype.hasOwnProperty.call(EventPrivacy, key)) {
            if (EventPrivacy[key as keyof typeof EventPrivacy] === value) {
                return true;
            }
        }
    }
    return false;
}

/**
 * Converts a JSON value to an `EventPrivacy` type.
 *
 * @returns The corresponding `EventPrivacy` value.
 */
export function EventPrivacyFromJSON(json: any): EventPrivacy {
    return EventPrivacyFromJSONTyped(json, false);
}

/**
 * Converts a JSON value to the `EventPrivacy` type without validation or transformation.
 *
 * @returns The input value cast as `EventPrivacy`
 */
export function EventPrivacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPrivacy {
    return json as EventPrivacy;
}

/**
 * Serializes an `EventPrivacy` value to JSON format.
 *
 * @returns The input value as a JSON-compatible value
 */
export function EventPrivacyToJSON(value?: EventPrivacy | null): any {
    return value as any;
}

/**
 * Casts the input value to the EventPrivacy type for JSON serialization.
 *
 * @param value - The value to be cast as EventPrivacy
 * @param ignoreDiscriminator - Unused parameter included for compatibility with code generation patterns
 * @returns The input value cast as EventPrivacy
 */
export function EventPrivacyToJSONTyped(value: any, ignoreDiscriminator: boolean): EventPrivacy {
    return value as EventPrivacy;
}

