/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
    UserInfoToJSONTyped,
} from './UserInfo';

/**
 * 
 * @export
 * @interface GetTopScoreUsers200ResponseInner
 */
export interface GetTopScoreUsers200ResponseInner {
    /**
     * 
     * @type {UserInfo}
     * @memberof GetTopScoreUsers200ResponseInner
     */
    user?: UserInfo;
    /**
     * The user's score
     * @type {number}
     * @memberof GetTopScoreUsers200ResponseInner
     */
    score?: number;
}

/**
 * Determines whether the provided object is treated as a `GetTopScoreUsers200ResponseInner` instance.
 *
 * Always returns `true`, so all objects are considered valid instances.
 */
export function instanceOfGetTopScoreUsers200ResponseInner(value: object): value is GetTopScoreUsers200ResponseInner {
    return true;
}

/**
 * Converts a JSON object to a `GetTopScoreUsers200ResponseInner` instance.
 *
 * @returns The corresponding `GetTopScoreUsers200ResponseInner` object
 */
export function GetTopScoreUsers200ResponseInnerFromJSON(json: any): GetTopScoreUsers200ResponseInner {
    return GetTopScoreUsers200ResponseInnerFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to a typed `GetTopScoreUsers200ResponseInner` instance.
 *
 * If the input is `null`, returns `null`. The `user` property is deserialized using `UserInfoFromJSON` if present; otherwise, it is set to `undefined`. The `score` property is assigned directly if present, or set to `undefined` if missing.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - If true, discriminator properties are ignored (not used in this implementation)
 * @returns The corresponding `GetTopScoreUsers200ResponseInner` instance, or `null` if input is `null`
 */
export function GetTopScoreUsers200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTopScoreUsers200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserInfoFromJSON(json['user']),
        'score': json['score'] == null ? undefined : json['score'],
    };
}

/**
 * Converts a JSON object to a `GetTopScoreUsers200ResponseInner` instance.
 *
 * @returns The deserialized `GetTopScoreUsers200ResponseInner` object
 */
export function GetTopScoreUsers200ResponseInnerToJSON(json: any): GetTopScoreUsers200ResponseInner {
    return GetTopScoreUsers200ResponseInnerToJSONTyped(json, false);
}

/**
 * Converts a `GetTopScoreUsers200ResponseInner` instance to a JSON object, serializing the `user` property if present.
 *
 * @param value - The `GetTopScoreUsers200ResponseInner` instance to convert, or `null`/`undefined`
 * @param ignoreDiscriminator - If true, discriminator properties are ignored (not used in this implementation)
 * @returns The JSON representation of the input instance, or `null`/`undefined` if the input is `null`/`undefined`
 */
export function GetTopScoreUsers200ResponseInnerToJSONTyped(value?: GetTopScoreUsers200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserInfoToJSON(value['user']),
        'score': value['score'],
    };
}

