/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Host
 */
export interface Host {
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    name?: string;
}

/**
 * Type guard that always treats any object as a `Host`.
 *
 * This function does not perform any property checks and always returns `true`.
 */
export function instanceOfHost(value: object): value is Host {
    return true;
}

/**
 * Converts a JSON object to a `Host` instance.
 *
 * @returns A `Host` object created from the provided JSON data.
 */
export function HostFromJSON(json: any): Host {
    return HostFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to a `Host` instance, mapping each property if present or setting it to `undefined` if absent.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - Ignored in this implementation; included for compatibility
 * @returns A `Host` object with properties populated from the JSON input, or `null`/`undefined` if the input is `null`/`undefined`
 */
export function HostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Host {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

/**
 * Converts a JSON object to a `Host` instance.
 *
 * @returns The corresponding `Host` object.
 */
export function HostToJSON(json: any): Host {
    return HostToJSONTyped(json, false);
}

/**
 * Serializes a `Host` object into a JSON-compatible object.
 *
 * @param value - The `Host` instance to serialize, or `null`/`undefined`
 * @returns A JSON object representing the `Host`, or the input if it is `null` or `undefined`
 */
export function HostToJSONTyped(value?: Host | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSlotId': value['eventSlotId'],
        'userId': value['userId'],
        'email': value['email'],
        'phone': value['phone'],
        'name': value['name'],
    };
}

