/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Host
 */
export interface Host {
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    name?: string;
}

/**
 * Check if a given object implements the Host interface.
 */
export function instanceOfHost(value: object): value is Host {
    return true;
}

export function HostFromJSON(json: any): Host {
    return HostFromJSONTyped(json, false);
}

export function HostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Host {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function HostToJSON(json: any): Host {
    return HostToJSONTyped(json, false);
}

export function HostToJSONTyped(value?: Host | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSlotId': value['eventSlotId'],
        'userId': value['userId'],
        'email': value['email'],
        'phone': value['phone'],
        'name': value['name'],
    };
}

