/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Like
 */
export interface Like {
    /**
     * 
     * @type {string}
     * @memberof Like
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Like
     */
    reaction?: string;
    /**
     * 
     * @type {Date}
     * @memberof Like
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the Like interface.
 */
export function instanceOfLike(value: object): value is Like {
    return true;
}

export function LikeFromJSON(json: any): Like {
    return LikeFromJSONTyped(json, false);
}

export function LikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Like {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'reaction': json['reaction'] == null ? undefined : json['reaction'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function LikeToJSON(json: any): Like {
    return LikeToJSONTyped(json, false);
}

export function LikeToJSONTyped(value?: Like | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'reaction': value['reaction'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

