/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object describing the date with the date and time. 
 * For simplicity the time is always in UTC, so no timezone is associated to the time. 
 * Time is only converted to the user's timezone when displayed in the frontend.
 * 
 * @export
 * @interface ModelDate
 */
export interface ModelDate {
    /**
     * 
     * @type {Date}
     * @memberof ModelDate
     */
    postedTime?: Date;
}

/**
 * Check if a given object implements the ModelDate interface.
 */
export function instanceOfModelDate(value: object): value is ModelDate {
    return true;
}

export function ModelDateFromJSON(json: any): ModelDate {
    return ModelDateFromJSONTyped(json, false);
}

export function ModelDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDate {
    if (json == null) {
        return json;
    }
    return {
        
        'postedTime': json['postedTime'] == null ? undefined : (new Date(json['postedTime'])),
    };
}

export function ModelDateToJSON(json: any): ModelDate {
    return ModelDateToJSONTyped(json, false);
}

export function ModelDateToJSONTyped(value?: ModelDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postedTime': value['postedTime'] == null ? undefined : ((value['postedTime']).toISOString()),
    };
}

