/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * The unique identifier for the offer.
     * @type {string}
     * @memberof Notification
     */
    id?: string;
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof Notification
     */
    userId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    emails?: Array<string>;
    /**
     * The unique identifier for the community.
     * @type {string}
     * @memberof Notification
     */
    communityId?: string;
    /**
     * The type of the notification.
     * @type {string}
     * @memberof Notification
     */
    notificationType: NotificationNotificationTypeEnum;
    /**
     * The image of the notification.
     * @type {string}
     * @memberof Notification
     */
    notificationImage?: string;
    /**
     * The name of the notification.
     * @type {string}
     * @memberof Notification
     */
    notificationTitle?: string;
    /**
     * The link of the notification.
     * @type {string}
     * @memberof Notification
     */
    notificationLink?: string;
    /**
     * The message of the notification.
     * @type {string}
     * @memberof Notification
     */
    notificationMessage?: string;
    /**
     * The type of entity related to the notification.
     * @type {string}
     * @memberof Notification
     */
    entityType: NotificationEntityTypeEnum;
    /**
     * The timestamp when the notification was created.
     * @type {string}
     * @memberof Notification
     */
    createdAt?: string;
    /**
     * The timestamp when the notification expires.
     * @type {string}
     * @memberof Notification
     */
    expiryDate?: string;
    /**
     * Indicates whether the email has been sent.
     * @type {boolean}
     * @memberof Notification
     */
    emailSent?: boolean;
    /**
     * Indicates whether the notification has been read.
     * @type {boolean}
     * @memberof Notification
     */
    read?: boolean;
}


/**
 * @export
 */
export const NotificationNotificationTypeEnum = {
    Oinked: 'OINKED',
    Tagged: 'TAGGED',
    Invited: 'INVITED',
    Accepted: 'ACCEPTED',
    Rejected: 'REJECTED',
    Commented: 'COMMENTED',
    Liked: 'LIKED',
    CommentLiked: 'COMMENT_LIKED',
    Followed: 'FOLLOWED',
    Subscribed: 'SUBSCRIBED',
    EventReminder: 'EVENT_REMINDER',
    EventCancelled: 'EVENT_CANCELLED',
    EventRescheduled: 'EVENT_RESCHEDULED',
    EventStarted: 'EVENT_STARTED',
    EventInvite: 'EVENT_INVITE',
    CommunityUpdate: 'COMMUNITY_UPDATE',
    CommunityInvite: 'COMMUNITY_INVITE',
    ProductShipped: 'PRODUCT_SHIPPED',
    ProductDelivered: 'PRODUCT_DELIVERED',
    ProductReturned: 'PRODUCT_RETURNED',
    ProductPurchased: 'PRODUCT_PURCHASED',
    ProductPurchased2: 'PRODUCT_PURCHASED'
} as const;
export type NotificationNotificationTypeEnum = typeof NotificationNotificationTypeEnum[keyof typeof NotificationNotificationTypeEnum];

/**
 * @export
 */
export const NotificationEntityTypeEnum = {
    Post: 'POST',
    Comment: 'COMMENT',
    Event: 'EVENT',
    Product: 'PRODUCT',
    Community: 'COMMUNITY'
} as const;
export type NotificationEntityTypeEnum = typeof NotificationEntityTypeEnum[keyof typeof NotificationEntityTypeEnum];


/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    if (!('entityType' in value) || value['entityType'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'emails': json['emails'] == null ? undefined : json['emails'],
        'communityId': json['communityId'] == null ? undefined : json['communityId'],
        'notificationType': json['notificationType'],
        'notificationImage': json['notificationImage'] == null ? undefined : json['notificationImage'],
        'notificationTitle': json['notificationTitle'] == null ? undefined : json['notificationTitle'],
        'notificationLink': json['notificationLink'] == null ? undefined : json['notificationLink'],
        'notificationMessage': json['notificationMessage'] == null ? undefined : json['notificationMessage'],
        'entityType': json['entityType'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'expiryDate': json['expiryDate'] == null ? undefined : json['expiryDate'],
        'emailSent': json['emailSent'] == null ? undefined : json['emailSent'],
        'read': json['read'] == null ? undefined : json['read'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'emails': value['emails'],
        'communityId': value['communityId'],
        'notificationType': value['notificationType'],
        'notificationImage': value['notificationImage'],
        'notificationTitle': value['notificationTitle'],
        'notificationLink': value['notificationLink'],
        'notificationMessage': value['notificationMessage'],
        'entityType': value['entityType'],
        'createdAt': value['createdAt'],
        'expiryDate': value['expiryDate'],
        'emailSent': value['emailSent'],
        'read': value['read'],
    };
}

