/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * The unique identifier for the offer.
     * @type {string}
     * @memberof Offer
     */
    id?: string;
    /**
     * The title of the offer.
     * @type {string}
     * @memberof Offer
     */
    title: string;
    /**
     * The description of the offer.
     * @type {string}
     * @memberof Offer
     */
    description: string;
    /**
     * The link to the offer.
     * @type {string}
     * @memberof Offer
     */
    offerLink: string;
    /**
     * 
     * @type {Status}
     * @memberof Offer
     */
    offerStatus: Status;
    /**
     * 
     * @type {Category}
     * @memberof Offer
     */
    offerType: Category;
}



/**
 * Check if a given object implements the Offer interface.
 */
export function instanceOfOffer(value: object): value is Offer {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('offerLink' in value) || value['offerLink'] === undefined) return false;
    if (!('offerStatus' in value) || value['offerStatus'] === undefined) return false;
    if (!('offerType' in value) || value['offerType'] === undefined) return false;
    return true;
}

export function OfferFromJSON(json: any): Offer {
    return OfferFromJSONTyped(json, false);
}

export function OfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Offer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'],
        'offerLink': json['offerLink'],
        'offerStatus': StatusFromJSON(json['offerStatus']),
        'offerType': CategoryFromJSON(json['offerType']),
    };
}

export function OfferToJSON(json: any): Offer {
    return OfferToJSONTyped(json, false);
}

export function OfferToJSONTyped(value?: Offer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'offerLink': value['offerLink'],
        'offerStatus': StatusToJSON(value['offerStatus']),
        'offerType': CategoryToJSON(value['offerType']),
    };
}

