/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Option
 */
export interface Option {
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    option: string;
    /**
     * 
     * @type {number}
     * @memberof Option
     */
    votes?: number;
}

/**
 * Check if a given object implements the Option interface.
 */
export function instanceOfOption(value: object): value is Option {
    if (!('option' in value) || value['option'] === undefined) return false;
    return true;
}

export function OptionFromJSON(json: any): Option {
    return OptionFromJSONTyped(json, false);
}

export function OptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Option {
    if (json == null) {
        return json;
    }
    return {
        
        'option': json['option'],
        'votes': json['votes'] == null ? undefined : json['votes'],
    };
}

export function OptionToJSON(json: any): Option {
    return OptionToJSONTyped(json, false);
}

export function OptionToJSONTyped(value?: Option | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'option': value['option'],
        'votes': value['votes'],
    };
}

