/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelDate } from './ModelDate';
import {
    ModelDateFromJSON,
    ModelDateFromJSONTyped,
    ModelDateToJSON,
    ModelDateToJSONTyped,
} from './ModelDate';

/**
 * 
 * @export
 * @interface PointsGift
 */
export interface PointsGift {
    /**
     * 
     * @type {string}
     * @memberof PointsGift
     */
    receivingUserId: string;
    /**
     * 
     * @type {string}
     * @memberof PointsGift
     */
    giverUserId: string;
    /**
     * 
     * @type {number}
     * @memberof PointsGift
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof PointsGift
     */
    pointType?: PointsGiftPointTypeEnum;
    /**
     * 
     * @type {ModelDate}
     * @memberof PointsGift
     */
    date?: ModelDate;
    /**
     * 
     * @type {string}
     * @memberof PointsGift
     */
    note?: string;
}


/**
 * @export
 */
export const PointsGiftPointTypeEnum = {
    Pig: 'PIG',
    Warthog: 'WARTHOG'
} as const;
export type PointsGiftPointTypeEnum = typeof PointsGiftPointTypeEnum[keyof typeof PointsGiftPointTypeEnum];


/**
 * Check if a given object implements the PointsGift interface.
 */
export function instanceOfPointsGift(value: object): value is PointsGift {
    if (!('receivingUserId' in value) || value['receivingUserId'] === undefined) return false;
    if (!('giverUserId' in value) || value['giverUserId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function PointsGiftFromJSON(json: any): PointsGift {
    return PointsGiftFromJSONTyped(json, false);
}

export function PointsGiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointsGift {
    if (json == null) {
        return json;
    }
    return {
        
        'receivingUserId': json['receivingUserId'],
        'giverUserId': json['giverUserId'],
        'score': json['score'],
        'pointType': json['pointType'] == null ? undefined : json['pointType'],
        'date': json['date'] == null ? undefined : ModelDateFromJSON(json['date']),
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function PointsGiftToJSON(json: any): PointsGift {
    return PointsGiftToJSONTyped(json, false);
}

export function PointsGiftToJSONTyped(value?: PointsGift | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receivingUserId': value['receivingUserId'],
        'giverUserId': value['giverUserId'],
        'score': value['score'],
        'pointType': value['pointType'],
        'date': ModelDateToJSON(value['date']),
        'note': value['note'],
    };
}

