/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Option } from './Option';
import {
    OptionFromJSON,
    OptionFromJSONTyped,
    OptionToJSON,
    OptionToJSONTyped,
} from './Option';

/**
 * 
 * @export
 * @interface Poll
 */
export interface Poll {
    /**
     * 
     * @type {string}
     * @memberof Poll
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Poll
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Poll
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Poll
     */
    question: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Poll
     */
    organizations?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Poll
     */
    rooms?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof Poll
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Poll
     */
    endDate: Date;
    /**
     * 
     * @type {Array<Option>}
     * @memberof Poll
     */
    options: Array<Option>;
    /**
     * 
     * @type {Status}
     * @memberof Poll
     */
    status?: Status;
}



/**
 * Check if a given object implements the Poll interface.
 */
export function instanceOfPoll(value: object): value is Poll {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function PollFromJSON(json: any): Poll {
    return PollFromJSONTyped(json, false);
}

export function PollFromJSONTyped(json: any, ignoreDiscriminator: boolean): Poll {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'question': json['question'],
        'organizations': json['organizations'] == null ? undefined : json['organizations'],
        'rooms': json['rooms'] == null ? undefined : json['rooms'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'options': ((json['options'] as Array<any>).map(OptionFromJSON)),
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
    };
}

export function PollToJSON(json: any): Poll {
    return PollToJSONTyped(json, false);
}

export function PollToJSONTyped(value?: Poll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'imageUrl': value['imageUrl'],
        'question': value['question'],
        'organizations': value['organizations'],
        'rooms': value['rooms'],
        'startDate': ((value['startDate']).toISOString()),
        'endDate': ((value['endDate']).toISOString()),
        'options': ((value['options'] as Array<any>).map(OptionToJSON)),
        'status': StatusToJSON(value['status']),
    };
}

