/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';
import type { Like } from './Like';
import {
    LikeFromJSON,
    LikeFromJSONTyped,
    LikeToJSON,
    LikeToJSONTyped,
} from './Like';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    newsfeedId?: string;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    posterUserId?: string;
    /**
     * 
     * @type {Array<Event>}
     * @memberof Post
     */
    eventV2?: Array<Event>;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    posterName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Post
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Array<Like>}
     * @memberof Post
     */
    likes?: Array<Like>;
    /**
     * 
     * @type {Array<Comment>}
     * @memberof Post
     */
    comments?: Array<Comment>;
    /**
     * 
     * @type {Date}
     * @memberof Post
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Post
     */
    modifiedAt?: Date;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
    return true;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'newsfeedId': json['newsfeedId'] == null ? undefined : json['newsfeedId'],
        'posterUserId': json['posterUserId'] == null ? undefined : json['posterUserId'],
        'eventV2': json['eventV2'] == null ? undefined : ((json['eventV2'] as Array<any>).map(EventFromJSON)),
        'posterName': json['posterName'] == null ? undefined : json['posterName'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'likes': json['likes'] == null ? undefined : ((json['likes'] as Array<any>).map(LikeFromJSON)),
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(CommentFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
    };
}

export function PostToJSON(json: any): Post {
    return PostToJSONTyped(json, false);
}

export function PostToJSONTyped(value?: Post | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'newsfeedId': value['newsfeedId'],
        'posterUserId': value['posterUserId'],
        'eventV2': value['eventV2'] == null ? undefined : ((value['eventV2'] as Array<any>).map(EventToJSON)),
        'posterName': value['posterName'],
        'tags': value['tags'],
        'likes': value['likes'] == null ? undefined : ((value['likes'] as Array<any>).map(LikeToJSON)),
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(CommentToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
    };
}

