/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PreferredLanguage = {
    En: 'EN',
    Es: 'ES',
    Fr: 'FR',
    De: 'DE',
    Hi: 'HI',
    Te: 'TE',
    Zh: 'ZH',
    Pl: 'PL',
    Ar: 'AR'
} as const;
export type PreferredLanguage = typeof PreferredLanguage[keyof typeof PreferredLanguage];


export function instanceOfPreferredLanguage(value: any): boolean {
    for (const key in PreferredLanguage) {
        if (Object.prototype.hasOwnProperty.call(PreferredLanguage, key)) {
            if (PreferredLanguage[key as keyof typeof PreferredLanguage] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PreferredLanguageFromJSON(json: any): PreferredLanguage {
    return PreferredLanguageFromJSONTyped(json, false);
}

export function PreferredLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferredLanguage {
    return json as PreferredLanguage;
}

export function PreferredLanguageToJSON(value?: PreferredLanguage | null): any {
    return value as any;
}

export function PreferredLanguageToJSONTyped(value: any, ignoreDiscriminator: boolean): PreferredLanguage {
    return value as PreferredLanguage;
}

