/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromoCode
 */
export interface PromoCode {
    /**
     * 
     * @type {string}
     * @memberof PromoCode
     */
    promoCode?: string;
    /**
     * 
     * @type {number}
     * @memberof PromoCode
     */
    percentageOff?: number;
}

/**
 * Determines whether the given object can be treated as a PromoCode.
 *
 * Always returns `true`, treating any object as a PromoCode regardless of its properties.
 */
export function instanceOfPromoCode(value: object): value is PromoCode {
    return true;
}

/**
 * Converts a JSON object to a `PromoCode` instance.
 *
 * @returns The corresponding `PromoCode` object.
 */
export function PromoCodeFromJSON(json: any): PromoCode {
    return PromoCodeFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to a `PromoCode` instance, mapping `promoCode` and `percentageOff` fields and setting them to `undefined` if they are `null` in the input.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - If true, discriminator properties are ignored (not used in this implementation)
 * @returns A `PromoCode` instance with mapped properties, or `null` if the input is `null`
 */
export function PromoCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoCode {
    if (json == null) {
        return json;
    }
    return {
        
        'promoCode': json['promoCode'] == null ? undefined : json['promoCode'],
        'percentageOff': json['percentageOff'] == null ? undefined : json['percentageOff'],
    };
}

/**
 * Converts a JSON object to a `PromoCode` instance.
 *
 * @returns The `PromoCode` representation of the input JSON.
 */
export function PromoCodeToJSON(json: any): PromoCode {
    return PromoCodeToJSONTyped(json, false);
}

/**
 * Converts a `PromoCode` instance to a JSON object, preserving `null` or `undefined` values.
 *
 * @param value - The `PromoCode` instance to convert, or `null`/`undefined`
 * @returns A JSON object representing the promo code, or the original value if `null` or `undefined`
 */
export function PromoCodeToJSONTyped(value?: PromoCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promoCode': value['promoCode'],
        'percentageOff': value['percentageOff'],
    };
}

