/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromoCode
 */
export interface PromoCode {
    /**
     * 
     * @type {string}
     * @memberof PromoCode
     */
    promoCode?: string;
    /**
     * 
     * @type {number}
     * @memberof PromoCode
     */
    percentageOff?: number;
}

/**
 * Check if a given object implements the PromoCode interface.
 */
export function instanceOfPromoCode(value: object): value is PromoCode {
    return true;
}

export function PromoCodeFromJSON(json: any): PromoCode {
    return PromoCodeFromJSONTyped(json, false);
}

export function PromoCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoCode {
    if (json == null) {
        return json;
    }
    return {
        
        'promoCode': json['promoCode'] == null ? undefined : json['promoCode'],
        'percentageOff': json['percentageOff'] == null ? undefined : json['percentageOff'],
    };
}

export function PromoCodeToJSON(json: any): PromoCode {
    return PromoCodeToJSONTyped(json, false);
}

export function PromoCodeToJSONTyped(value?: PromoCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promoCode': value['promoCode'],
        'percentageOff': value['percentageOff'],
    };
}

