/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface PushNotification
 */
export interface PushNotification {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof PushNotification
     */
    userId: string;
    /**
     * The device token for the user.
     * @type {string}
     * @memberof PushNotification
     */
    deviceToken: string;
    /**
     * The platform of the user.
     * @type {string}
     * @memberof PushNotification
     */
    platform: PushNotificationPlatformEnum;
    /**
     * The version of the app.
     * @type {string}
     * @memberof PushNotification
     */
    appVersion?: string;
    /**
     * Whether the device token is active.
     * @type {boolean}
     * @memberof PushNotification
     */
    isActive: boolean;
    /**
     * The date and time the device token was created.
     * @type {Date}
     * @memberof PushNotification
     */
    createdAt: Date;
    /**
     * The date and time the device token was updated.
     * @type {Date}
     * @memberof PushNotification
     */
    deviceTokenUpdatedAt?: Date;
    /**
     * The unique identifier for the device token.
     * @type {string}
     * @memberof PushNotification
     */
    deviceTokenId: string;
    /**
     * 
     * @type {Notification}
     * @memberof PushNotification
     */
    notification: Notification;
    /**
     * 
     * @type {User}
     * @memberof PushNotification
     */
    user?: User;
}


/**
 * @export
 */
export const PushNotificationPlatformEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web'
} as const;
export type PushNotificationPlatformEnum = typeof PushNotificationPlatformEnum[keyof typeof PushNotificationPlatformEnum];


/**
 * Check if a given object implements the PushNotification interface.
 */
export function instanceOfPushNotification(value: object): value is PushNotification {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('deviceToken' in value) || value['deviceToken'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deviceTokenId' in value) || value['deviceTokenId'] === undefined) return false;
    if (!('notification' in value) || value['notification'] === undefined) return false;
    return true;
}

export function PushNotificationFromJSON(json: any): PushNotification {
    return PushNotificationFromJSONTyped(json, false);
}

export function PushNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'deviceToken': json['deviceToken'],
        'platform': json['platform'],
        'appVersion': json['appVersion'] == null ? undefined : json['appVersion'],
        'isActive': json['isActive'],
        'createdAt': (new Date(json['createdAt'])),
        'deviceTokenUpdatedAt': json['deviceTokenUpdatedAt'] == null ? undefined : (new Date(json['deviceTokenUpdatedAt'])),
        'deviceTokenId': json['deviceTokenId'],
        'notification': NotificationFromJSON(json['notification']),
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
    };
}

export function PushNotificationToJSON(json: any): PushNotification {
    return PushNotificationToJSONTyped(json, false);
}

export function PushNotificationToJSONTyped(value?: PushNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'deviceToken': value['deviceToken'],
        'platform': value['platform'],
        'appVersion': value['appVersion'],
        'isActive': value['isActive'],
        'createdAt': ((value['createdAt']).toISOString()),
        'deviceTokenUpdatedAt': value['deviceTokenUpdatedAt'] == null ? undefined : ((value['deviceTokenUpdatedAt']).toISOString()),
        'deviceTokenId': value['deviceTokenId'],
        'notification': NotificationToJSON(value['notification']),
        'user': UserToJSON(value['user']),
    };
}

