/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Recurrence
 */
export interface Recurrence {
    /**
     * 
     * @type {string}
     * @memberof Recurrence
     */
    frequency?: RecurrenceFrequencyEnum;
    /**
     * 
     * @type {number}
     * @memberof Recurrence
     */
    interval?: number;
    /**
     * 
     * @type {number}
     * @memberof Recurrence
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof Recurrence
     */
    byDay?: RecurrenceByDayEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof Recurrence
     */
    byMonthDay?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Recurrence
     */
    byMonth?: Array<number>;
}


/**
 * @export
 */
export const RecurrenceFrequencyEnum = {
    Daily: 'DAILY',
    Weekly: 'WEEKLY',
    Monthly: 'MONTHLY',
    Yearly: 'YEARLY'
} as const;
export type RecurrenceFrequencyEnum = typeof RecurrenceFrequencyEnum[keyof typeof RecurrenceFrequencyEnum];

/**
 * @export
 */
export const RecurrenceByDayEnum = {
    Mon: 'MON',
    Tue: 'TUE',
    Wed: 'WED',
    Thu: 'THU',
    Fri: 'FRI',
    Sat: 'SAT',
    Sun: 'SUN'
} as const;
export type RecurrenceByDayEnum = typeof RecurrenceByDayEnum[keyof typeof RecurrenceByDayEnum];


/**
 * Check if a given object implements the Recurrence interface.
 */
export function instanceOfRecurrence(value: object): value is Recurrence {
    return true;
}

export function RecurrenceFromJSON(json: any): Recurrence {
    return RecurrenceFromJSONTyped(json, false);
}

export function RecurrenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recurrence {
    if (json == null) {
        return json;
    }
    return {
        
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'count': json['count'] == null ? undefined : json['count'],
        'byDay': json['byDay'] == null ? undefined : json['byDay'],
        'byMonthDay': json['byMonthDay'] == null ? undefined : json['byMonthDay'],
        'byMonth': json['byMonth'] == null ? undefined : json['byMonth'],
    };
}

export function RecurrenceToJSON(json: any): Recurrence {
    return RecurrenceToJSONTyped(json, false);
}

export function RecurrenceToJSONTyped(value?: Recurrence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'frequency': value['frequency'],
        'interval': value['interval'],
        'count': value['count'],
        'byDay': value['byDay'],
        'byMonthDay': value['byMonthDay'],
        'byMonth': value['byMonth'],
    };
}

