/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * The unique identifier for the resource.
     * @type {string}
     * @memberof Resource
     */
    id?: string;
    /**
     * The title of the resource.
     * @type {string}
     * @memberof Resource
     */
    title: string;
    /**
     * The description of the resource.
     * @type {string}
     * @memberof Resource
     */
    description: string;
    /**
     * The link to the resource.
     * @type {string}
     * @memberof Resource
     */
    resourceLink: string;
    /**
     * 
     * @type {Status}
     * @memberof Resource
     */
    resourceStatus: Status;
    /**
     * 
     * @type {Category}
     * @memberof Resource
     */
    resourceType: Category;
}



/**
 * Check if a given object implements the Resource interface.
 */
export function instanceOfResource(value: object): value is Resource {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('resourceLink' in value) || value['resourceLink'] === undefined) return false;
    if (!('resourceStatus' in value) || value['resourceStatus'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    return true;
}

export function ResourceFromJSON(json: any): Resource {
    return ResourceFromJSONTyped(json, false);
}

export function ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Resource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'],
        'resourceLink': json['resourceLink'],
        'resourceStatus': StatusFromJSON(json['resourceStatus']),
        'resourceType': CategoryFromJSON(json['resourceType']),
    };
}

export function ResourceToJSON(json: any): Resource {
    return ResourceToJSONTyped(json, false);
}

export function ResourceToJSONTyped(value?: Resource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'resourceLink': value['resourceLink'],
        'resourceStatus': StatusToJSON(value['resourceStatus']),
        'resourceType': CategoryToJSON(value['resourceType']),
    };
}

