/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RSVPStatus } from './RSVPStatus';
import {
    RSVPStatusFromJSON,
    RSVPStatusFromJSONTyped,
    RSVPStatusToJSON,
    RSVPStatusToJSONTyped,
} from './RSVPStatus';

/**
 * 
 * @export
 * @interface RSVP
 */
export interface RSVP {
    /**
     * 
     * @type {string}
     * @memberof RSVP
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RSVP
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof RSVP
     */
    userId?: string;
    /**
     * 
     * @type {RSVPStatus}
     * @memberof RSVP
     */
    rsvpStatus?: RSVPStatus;
}



/**
 * Check if a given object implements the RSVP interface.
 */
export function instanceOfRSVP(value: object): value is RSVP {
    return true;
}

export function RSVPFromJSON(json: any): RSVP {
    return RSVPFromJSONTyped(json, false);
}

export function RSVPFromJSONTyped(json: any, ignoreDiscriminator: boolean): RSVP {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'rsvpStatus': json['rsvpStatus'] == null ? undefined : RSVPStatusFromJSON(json['rsvpStatus']),
    };
}

export function RSVPToJSON(json: any): RSVP {
    return RSVPToJSONTyped(json, false);
}

export function RSVPToJSONTyped(value?: RSVP | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventSlotId': value['eventSlotId'],
        'userId': value['userId'],
        'rsvpStatus': RSVPStatusToJSON(value['rsvpStatus']),
    };
}

