/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RSVPStatus = {
    Going: 'GOING',
    NotGoing: 'NOT_GOING'
} as const;
export type RSVPStatus = typeof RSVPStatus[keyof typeof RSVPStatus];


export function instanceOfRSVPStatus(value: any): boolean {
    for (const key in RSVPStatus) {
        if (Object.prototype.hasOwnProperty.call(RSVPStatus, key)) {
            if (RSVPStatus[key as keyof typeof RSVPStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RSVPStatusFromJSON(json: any): RSVPStatus {
    return RSVPStatusFromJSONTyped(json, false);
}

export function RSVPStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RSVPStatus {
    return json as RSVPStatus;
}

export function RSVPStatusToJSON(value?: RSVPStatus | null): any {
    return value as any;
}

export function RSVPStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RSVPStatus {
    return value as RSVPStatus;
}

