/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RSVPStatus } from './RSVPStatus';
import {
    RSVPStatusFromJSON,
    RSVPStatusFromJSONTyped,
    RSVPStatusToJSON,
    RSVPStatusToJSONTyped,
} from './RSVPStatus';

/**
 * 
 * @export
 * @interface RSVP
 */
export interface RSVP {
    /**
     * 
     * @type {string}
     * @memberof RSVP
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RSVP
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof RSVP
     */
    userId?: string;
    /**
     * 
     * @type {RSVPStatus}
     * @memberof RSVP
     */
    rsvpStatus?: RSVPStatus;
}



/**
 * Determines whether the given object can be treated as an RSVP.
 *
 * Always returns `true`, regardless of the object's properties.
 */
export function instanceOfRSVP(value: object): value is RSVP {
    return true;
}

/**
 * Converts a JSON object to an RSVP instance.
 *
 * @returns An RSVP object created from the provided JSON data
 */
export function RSVPFromJSON(json: any): RSVP {
    return RSVPFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to an RSVP instance, optionally handling discriminator properties.
 *
 * If the input is `null`, returns `null`. Properties missing or set to `null` in the JSON are mapped to `undefined` in the resulting RSVP object. The `rsvpStatus` property is converted using `RSVPStatusFromJSON`.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - Whether to ignore discriminator properties during conversion
 * @returns The resulting RSVP object, or `null` if the input is `null`
 */
export function RSVPFromJSONTyped(json: any, ignoreDiscriminator: boolean): RSVP {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'rsvpStatus': json['rsvpStatus'] == null ? undefined : RSVPStatusFromJSON(json['rsvpStatus']),
    };
}

/**
 * Converts a JSON object to an RSVP instance.
 *
 * @returns The RSVP object created from the input JSON.
 */
export function RSVPToJSON(json: any): RSVP {
    return RSVPToJSONTyped(json, false);
}

/**
 * Converts an RSVP object to a JSON representation, with optional discriminator handling.
 *
 * @param value - The RSVP object to convert, or null/undefined
 * @param ignoreDiscriminator - If true, discriminator properties are ignored during conversion
 * @returns The JSON representation of the RSVP object, or null/undefined if input is null/undefined
 */
export function RSVPToJSONTyped(value?: RSVP | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventSlotId': value['eventSlotId'],
        'userId': value['userId'],
        'rsvpStatus': RSVPStatusToJSON(value['rsvpStatus']),
    };
}

