/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreLedger
 */
export interface ScoreLedger {
    /**
     * 
     * @type {number}
     * @memberof ScoreLedger
     */
    points: number;
    /**
     * 
     * @type {string}
     * @memberof ScoreLedger
     */
    action: string;
    /**
     * 
     * @type {Date}
     * @memberof ScoreLedger
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the ScoreLedger interface.
 */
export function instanceOfScoreLedger(value: object): value is ScoreLedger {
    if (!('points' in value) || value['points'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function ScoreLedgerFromJSON(json: any): ScoreLedger {
    return ScoreLedgerFromJSONTyped(json, false);
}

export function ScoreLedgerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreLedger {
    if (json == null) {
        return json;
    }
    return {
        
        'points': json['Points'],
        'action': json['Action'],
        'timestamp': json['Timestamp'] == null ? undefined : (new Date(json['Timestamp'])),
    };
}

export function ScoreLedgerToJSON(json: any): ScoreLedger {
    return ScoreLedgerToJSONTyped(json, false);
}

export function ScoreLedgerToJSONTyped(value?: ScoreLedger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Points': value['points'],
        'Action': value['action'],
        'Timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

