/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Actions } from './Actions';
import {
    ActionsFromJSON,
    ActionsFromJSONTyped,
    ActionsToJSON,
    ActionsToJSONTyped,
} from './Actions';

/**
 * 
 * @export
 * @interface ScoreReason
 */
export interface ScoreReason {
    /**
     * 
     * @type {Actions}
     * @memberof ScoreReason
     */
    action: Actions;
    /**
     * 
     * @type {number}
     * @memberof ScoreReason
     */
    score: number;
}



/**
 * Check if a given object implements the ScoreReason interface.
 */
export function instanceOfScoreReason(value: object): value is ScoreReason {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function ScoreReasonFromJSON(json: any): ScoreReason {
    return ScoreReasonFromJSONTyped(json, false);
}

export function ScoreReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreReason {
    if (json == null) {
        return json;
    }
    return {
        
        'action': ActionsFromJSON(json['action']),
        'score': json['score'],
    };
}

export function ScoreReasonToJSON(json: any): ScoreReason {
    return ScoreReasonToJSONTyped(json, false);
}

export function ScoreReasonToJSONTyped(value?: ScoreReason | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ActionsToJSON(value['action']),
        'score': value['score'],
    };
}

