/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendBulkEmail404Response
 */
export interface SendBulkEmail404Response {
    /**
     * 
     * @type {string}
     * @memberof SendBulkEmail404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the SendBulkEmail404Response interface.
 */
export function instanceOfSendBulkEmail404Response(value: object): value is SendBulkEmail404Response {
    return true;
}

export function SendBulkEmail404ResponseFromJSON(json: any): SendBulkEmail404Response {
    return SendBulkEmail404ResponseFromJSONTyped(json, false);
}

export function SendBulkEmail404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendBulkEmail404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SendBulkEmail404ResponseToJSON(json: any): SendBulkEmail404Response {
    return SendBulkEmail404ResponseToJSONTyped(json, false);
}

export function SendBulkEmail404ResponseToJSONTyped(value?: SendBulkEmail404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

