/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendBulkEmail500Response
 */
export interface SendBulkEmail500Response {
    /**
     * 
     * @type {string}
     * @memberof SendBulkEmail500Response
     */
    error?: string;
}

/**
 * Check if a given object implements the SendBulkEmail500Response interface.
 */
export function instanceOfSendBulkEmail500Response(value: object): value is SendBulkEmail500Response {
    return true;
}

export function SendBulkEmail500ResponseFromJSON(json: any): SendBulkEmail500Response {
    return SendBulkEmail500ResponseFromJSONTyped(json, false);
}

export function SendBulkEmail500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendBulkEmail500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SendBulkEmail500ResponseToJSON(json: any): SendBulkEmail500Response {
    return SendBulkEmail500ResponseToJSONTyped(json, false);
}

export function SendBulkEmail500ResponseToJSONTyped(value?: SendBulkEmail500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

