/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendWeeklyEventsDigest200Response
 */
export interface SendWeeklyEventsDigest200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SendWeeklyEventsDigest200Response
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SendWeeklyEventsDigest200Response
     */
    usersProcessed?: number;
    /**
     * 
     * @type {number}
     * @memberof SendWeeklyEventsDigest200Response
     */
    emailsSent?: number;
    /**
     * 
     * @type {string}
     * @memberof SendWeeklyEventsDigest200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the SendWeeklyEventsDigest200Response interface.
 */
export function instanceOfSendWeeklyEventsDigest200Response(value: object): value is SendWeeklyEventsDigest200Response {
    return true;
}

export function SendWeeklyEventsDigest200ResponseFromJSON(json: any): SendWeeklyEventsDigest200Response {
    return SendWeeklyEventsDigest200ResponseFromJSONTyped(json, false);
}

export function SendWeeklyEventsDigest200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendWeeklyEventsDigest200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'usersProcessed': json['usersProcessed'] == null ? undefined : json['usersProcessed'],
        'emailsSent': json['emailsSent'] == null ? undefined : json['emailsSent'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SendWeeklyEventsDigest200ResponseToJSON(json: any): SendWeeklyEventsDigest200Response {
    return SendWeeklyEventsDigest200ResponseToJSONTyped(json, false);
}

export function SendWeeklyEventsDigest200ResponseToJSONTyped(value?: SendWeeklyEventsDigest200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'usersProcessed': value['usersProcessed'],
        'emailsSent': value['emailsSent'],
        'message': value['message'],
    };
}

