/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendWeeklyEventsDigestToUsersRequest
 */
export interface SendWeeklyEventsDigestToUsersRequest {
    /**
     * Array of user IDs to send the digest to
     * @type {Array<string>}
     * @memberof SendWeeklyEventsDigestToUsersRequest
     */
    userIds: Array<string>;
}

/**
 * Check if a given object implements the SendWeeklyEventsDigestToUsersRequest interface.
 */
export function instanceOfSendWeeklyEventsDigestToUsersRequest(value: object): value is SendWeeklyEventsDigestToUsersRequest {
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function SendWeeklyEventsDigestToUsersRequestFromJSON(json: any): SendWeeklyEventsDigestToUsersRequest {
    return SendWeeklyEventsDigestToUsersRequestFromJSONTyped(json, false);
}

export function SendWeeklyEventsDigestToUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendWeeklyEventsDigestToUsersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIds': json['userIds'],
    };
}

export function SendWeeklyEventsDigestToUsersRequestToJSON(json: any): SendWeeklyEventsDigestToUsersRequest {
    return SendWeeklyEventsDigestToUsersRequestToJSONTyped(json, false);
}

export function SendWeeklyEventsDigestToUsersRequestToJSONTyped(value?: SendWeeklyEventsDigestToUsersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userIds': value['userIds'],
    };
}

