/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Social
 */
export interface Social {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof Social
     */
    userId?: string;
    /**
     * The Facebook profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    facebook?: string;
    /**
     * The Twitter profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    twitter?: string;
    /**
     * The Instagram profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    instagram?: string;
    /**
     * The LinkedIn profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    linkedin?: string;
    /**
     * The TikTok profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    tiktok?: string;
    /**
     * The YouTube channel URL of the user.
     * @type {string}
     * @memberof Social
     */
    youtube?: string;
    /**
     * The Twitch profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    twitch?: string;
    /**
     * The Snapchat profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    snapchat?: string;
    /**
     * The Discord profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    discord?: string;
    /**
     * The Medium profile URL of the user.
     * @type {string}
     * @memberof Social
     */
    medium?: string;
    /**
     * The primary website URL of the user.
     * @type {string}
     * @memberof Social
     */
    website?: string;
    /**
     * The secondary website URL of the user.
     * @type {string}
     * @memberof Social
     */
    website2?: string;
    /**
     * The tertiary website URL of the user.
     * @type {string}
     * @memberof Social
     */
    website3?: string;
}

/**
 * Check if a given object implements the Social interface.
 */
export function instanceOfSocial(value: object): value is Social {
    return true;
}

export function SocialFromJSON(json: any): Social {
    return SocialFromJSONTyped(json, false);
}

export function SocialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Social {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'facebook': json['facebook'] == null ? undefined : json['facebook'],
        'twitter': json['twitter'] == null ? undefined : json['twitter'],
        'instagram': json['instagram'] == null ? undefined : json['instagram'],
        'linkedin': json['linkedin'] == null ? undefined : json['linkedin'],
        'tiktok': json['tiktok'] == null ? undefined : json['tiktok'],
        'youtube': json['youtube'] == null ? undefined : json['youtube'],
        'twitch': json['twitch'] == null ? undefined : json['twitch'],
        'snapchat': json['snapchat'] == null ? undefined : json['snapchat'],
        'discord': json['discord'] == null ? undefined : json['discord'],
        'medium': json['medium'] == null ? undefined : json['medium'],
        'website': json['website'] == null ? undefined : json['website'],
        'website2': json['website2'] == null ? undefined : json['website2'],
        'website3': json['website3'] == null ? undefined : json['website3'],
    };
}

export function SocialToJSON(json: any): Social {
    return SocialToJSONTyped(json, false);
}

export function SocialToJSONTyped(value?: Social | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'facebook': value['facebook'],
        'twitter': value['twitter'],
        'instagram': value['instagram'],
        'linkedin': value['linkedin'],
        'tiktok': value['tiktok'],
        'youtube': value['youtube'],
        'twitch': value['twitch'],
        'snapchat': value['snapchat'],
        'discord': value['discord'],
        'medium': value['medium'],
        'website': value['website'],
        'website2': value['website2'],
        'website3': value['website3'],
    };
}

