/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SponsorImage
 */
export interface SponsorImage {
    /**
     * 
     * @type {string}
     * @memberof SponsorImage
     */
    uri?: string;
    /**
     * 
     * @type {string}
     * @memberof SponsorImage
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SponsorImage
     */
    type?: string;
}

/**
 * Check if a given object implements the SponsorImage interface.
 */
export function instanceOfSponsorImage(value: object): value is SponsorImage {
    return true;
}

export function SponsorImageFromJSON(json: any): SponsorImage {
    return SponsorImageFromJSONTyped(json, false);
}

export function SponsorImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SponsorImage {
    if (json == null) {
        return json;
    }
    return {
        
        'uri': json['uri'] == null ? undefined : json['uri'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SponsorImageToJSON(json: any): SponsorImage {
    return SponsorImageToJSONTyped(json, false);
}

export function SponsorImageToJSONTyped(value?: SponsorImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uri': value['uri'],
        'name': value['name'],
        'type': value['type'],
    };
}

