/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SponsorImage } from './SponsorImage';
import {
    SponsorImageFromJSON,
    SponsorImageFromJSONTyped,
    SponsorImageToJSON,
    SponsorImageToJSONTyped,
} from './SponsorImage';

/**
 * 
 * @export
 * @interface Sponsor
 */
export interface Sponsor {
    /**
     * 
     * @type {string}
     * @memberof Sponsor
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof Sponsor
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Sponsor
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Sponsor
     */
    description?: string;
    /**
     * 
     * @type {SponsorImage}
     * @memberof Sponsor
     */
    image?: SponsorImage;
    /**
     * 
     * @type {string}
     * @memberof Sponsor
     */
    link?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Sponsor
     */
    featured?: boolean;
}

/**
 * Check if a given object implements the Sponsor interface.
 */
export function instanceOfSponsor(value: object): value is Sponsor {
    return true;
}

export function SponsorFromJSON(json: any): Sponsor {
    return SponsorFromJSONTyped(json, false);
}

export function SponsorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sponsor {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'] == null ? undefined : SponsorImageFromJSON(json['image']),
        'link': json['link'] == null ? undefined : json['link'],
        'featured': json['featured'] == null ? undefined : json['featured'],
    };
}

export function SponsorToJSON(json: any): Sponsor {
    return SponsorToJSONTyped(json, false);
}

export function SponsorToJSONTyped(value?: Sponsor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSlotId': value['eventSlotId'],
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'image': SponsorImageToJSON(value['image']),
        'link': value['link'],
        'featured': value['featured'],
    };
}

