/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { ModelDate } from './ModelDate';
import {
    ModelDateFromJSON,
    ModelDateFromJSONTyped,
    ModelDateToJSON,
    ModelDateToJSONTyped,
} from './ModelDate';
import type { Subscriber } from './Subscriber';
import {
    SubscriberFromJSON,
    SubscriberFromJSONTyped,
    SubscriberToJSON,
    SubscriberToJSONTyped,
} from './Subscriber';

/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * The unique identifier for the user.
     * @type {string}
     * @memberof Subscription
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    subscriptionPrice: number;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscription
     */
    lastPaymentDate?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscription
     */
    nextPaymentDate?: ModelDate;
    /**
     * 
     * @type {Array<Subscriber>}
     * @memberof Subscription
     */
    subscribers?: Array<Subscriber>;
    /**
     * 
     * @type {Address}
     * @memberof Subscription
     */
    address?: Address;
    /**
     * 
     * @type {Status}
     * @memberof Subscription
     */
    status?: Status;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscription
     */
    createdAt?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscription
     */
    modifiedAt?: ModelDate;
}



/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('subscriptionPrice' in value) || value['subscriptionPrice'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'subscriptionPrice': json['subscriptionPrice'],
        'lastPaymentDate': json['lastPaymentDate'] == null ? undefined : ModelDateFromJSON(json['lastPaymentDate']),
        'nextPaymentDate': json['nextPaymentDate'] == null ? undefined : ModelDateFromJSON(json['nextPaymentDate']),
        'subscribers': json['subscribers'] == null ? undefined : ((json['subscribers'] as Array<any>).map(SubscriberFromJSON)),
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
        'createdAt': json['createdAt'] == null ? undefined : ModelDateFromJSON(json['createdAt']),
        'modifiedAt': json['modifiedAt'] == null ? undefined : ModelDateFromJSON(json['modifiedAt']),
    };
}

export function SubscriptionToJSON(json: any): Subscription {
    return SubscriptionToJSONTyped(json, false);
}

export function SubscriptionToJSONTyped(value?: Subscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'subscriptionPrice': value['subscriptionPrice'],
        'lastPaymentDate': ModelDateToJSON(value['lastPaymentDate']),
        'nextPaymentDate': ModelDateToJSON(value['nextPaymentDate']),
        'subscribers': value['subscribers'] == null ? undefined : ((value['subscribers'] as Array<any>).map(SubscriberToJSON)),
        'address': AddressToJSON(value['address']),
        'status': StatusToJSON(value['status']),
        'createdAt': ModelDateToJSON(value['createdAt']),
        'modifiedAt': ModelDateToJSON(value['modifiedAt']),
    };
}

