/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelDate } from './ModelDate';
import {
    ModelDateFromJSON,
    ModelDateFromJSONTyped,
    ModelDateToJSON,
    ModelDateToJSONTyped,
} from './ModelDate';

/**
 * 
 * @export
 * @interface Subscriber
 */
export interface Subscriber {
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof Subscriber
     */
    subscriptionPrice?: number;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscriber
     */
    dateSubscribed?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscriber
     */
    lastPaymentDate?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscriber
     */
    nextPaymentDate?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof Subscriber
     */
    cancelledAt?: ModelDate;
}

/**
 * Check if a given object implements the Subscriber interface.
 */
export function instanceOfSubscriber(value: object): value is Subscriber {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function SubscriberFromJSON(json: any): Subscriber {
    return SubscriberFromJSONTyped(json, false);
}

export function SubscriberFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscriber {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'subscriptionPrice': json['subscriptionPrice'] == null ? undefined : json['subscriptionPrice'],
        'dateSubscribed': json['dateSubscribed'] == null ? undefined : ModelDateFromJSON(json['dateSubscribed']),
        'lastPaymentDate': json['lastPaymentDate'] == null ? undefined : ModelDateFromJSON(json['lastPaymentDate']),
        'nextPaymentDate': json['nextPaymentDate'] == null ? undefined : ModelDateFromJSON(json['nextPaymentDate']),
        'cancelledAt': json['cancelledAt'] == null ? undefined : ModelDateFromJSON(json['cancelledAt']),
    };
}

export function SubscriberToJSON(json: any): Subscriber {
    return SubscriberToJSONTyped(json, false);
}

export function SubscriberToJSONTyped(value?: Subscriber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'subscriptionPrice': value['subscriptionPrice'],
        'dateSubscribed': ModelDateToJSON(value['dateSubscribed']),
        'lastPaymentDate': ModelDateToJSON(value['lastPaymentDate']),
        'nextPaymentDate': ModelDateToJSON(value['nextPaymentDate']),
        'cancelledAt': ModelDateToJSON(value['cancelledAt']),
    };
}

