/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Amount } from './Amount';
import {
    AmountFromJSON,
    AmountFromJSONTyped,
    AmountToJSON,
    AmountToJSONTyped,
} from './Amount';

/**
 * 
 * @export
 * @interface Ticket
 */
export interface Ticket {
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    eventSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    eventId?: string;
    /**
     * 
     * @type {Amount}
     * @memberof Ticket
     */
    ticketOption?: Amount;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    qrCode?: string;
    /**
     * 
     * @type {Date}
     * @memberof Ticket
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ticket
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    promoCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Ticket
     */
    ticketStatus?: TicketTicketStatusEnum;
}


/**
 * @export
 */
export const TicketTicketStatusEnum = {
    Sold: 'SOLD',
    Refunded: 'REFUNDED',
    CheckedIn: 'CHECKED_IN',
    Cancelled: 'CANCELLED',
    Pending: 'PENDING'
} as const;
export type TicketTicketStatusEnum = typeof TicketTicketStatusEnum[keyof typeof TicketTicketStatusEnum];


/**
 * Check if a given object implements the Ticket interface.
 */
export function instanceOfTicket(value: object): value is Ticket {
    return true;
}

export function TicketFromJSON(json: any): Ticket {
    return TicketFromJSONTyped(json, false);
}

export function TicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ticket {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventSlotId': json['eventSlotId'] == null ? undefined : json['eventSlotId'],
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'ticketOption': json['ticketOption'] == null ? undefined : AmountFromJSON(json['ticketOption']),
        'qrCode': json['qrCode'] == null ? undefined : json['qrCode'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'promoCode': json['promoCode'] == null ? undefined : json['promoCode'],
        'ticketStatus': json['ticketStatus'] == null ? undefined : json['ticketStatus'],
    };
}

export function TicketToJSON(json: any): Ticket {
    return TicketToJSONTyped(json, false);
}

export function TicketToJSONTyped(value?: Ticket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventSlotId': value['eventSlotId'],
        'eventId': value['eventId'],
        'ticketOption': AmountToJSON(value['ticketOption']),
        'qrCode': value['qrCode'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'userId': value['userId'],
        'username': value['username'],
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'promoCode': value['promoCode'],
        'ticketStatus': value['ticketStatus'],
    };
}

