/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketOptions
 */
export interface TicketOptions {
    /**
     * 
     * @type {string}
     * @memberof TicketOptions
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketOptions
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketOptions
     */
    eventId: string;
    /**
     * 
     * @type {number}
     * @memberof TicketOptions
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof TicketOptions
     */
    maxQuantity?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TicketOptions
     */
    anyPrice?: boolean;
    /**
     * Price in the event's currency, if applicable. If `anyPrice` is true, this field may be omitted.
     * @type {number}
     * @memberof TicketOptions
     */
    price?: number;
}

/**
 * Determines whether the provided object conforms to the TicketOptions interface by verifying the presence of the required `eventId` property.
 *
 * @returns `true` if the object has a defined `eventId` property; otherwise, `false`.
 */
export function instanceOfTicketOptions(value: object): value is TicketOptions {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    return true;
}

/**
 * Converts a JSON object to a `TicketOptions` instance.
 *
 * @param json - The JSON object to convert
 * @returns The corresponding `TicketOptions` object
 */
export function TicketOptionsFromJSON(json: any): TicketOptions {
    return TicketOptionsFromJSONTyped(json, false);
}

/**
 * Converts a JSON object to a `TicketOptions` instance, mapping each property and setting optional fields to `undefined` if missing or null.
 *
 * @param json - The JSON object to convert
 * @param ignoreDiscriminator - If true, discriminator properties are ignored during conversion
 * @returns The corresponding `TicketOptions` object, or `null` if the input is `null`
 */
export function TicketOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'eventId': json['eventId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'maxQuantity': json['maxQuantity'] == null ? undefined : json['maxQuantity'],
        'anyPrice': json['anyPrice'] == null ? undefined : json['anyPrice'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

/**
 * Converts a JSON object to a `TicketOptions` instance.
 *
 * @returns The corresponding `TicketOptions` object
 */
export function TicketOptionsToJSON(json: any): TicketOptions {
    return TicketOptionsToJSONTyped(json, false);
}

/**
 * Converts a `TicketOptions` object to a plain JSON representation.
 *
 * @param value - The `TicketOptions` object to convert, or `null`/`undefined` to return as-is
 * @param ignoreDiscriminator - If true, discriminator properties are ignored (not used in this implementation)
 * @returns A JSON object representing the `TicketOptions`, or `null`/`undefined` if the input is `null`/`undefined`
 */
export function TicketOptionsToJSONTyped(value?: TicketOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'eventId': value['eventId'],
        'quantity': value['quantity'],
        'maxQuantity': value['maxQuantity'],
        'anyPrice': value['anyPrice'],
        'price': value['price'],
    };
}

