/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketAnswers
 */
export interface TicketAnswers {
    /**
     * 
     * @type {string}
     * @memberof TicketAnswers
     */
    questionId?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAnswers
     */
    questionText?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketAnswers
     */
    answer?: string;
}

/**
 * Check if a given object implements the TicketAnswers interface.
 */
export function instanceOfTicketAnswers(value: object): value is TicketAnswers {
    return true;
}

export function TicketAnswersFromJSON(json: any): TicketAnswers {
    return TicketAnswersFromJSONTyped(json, false);
}

export function TicketAnswersFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketAnswers {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'questionText': json['questionText'] == null ? undefined : json['questionText'],
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function TicketAnswersToJSON(json: any): TicketAnswers {
    return TicketAnswersToJSONTyped(json, false);
}

export function TicketAnswersToJSONTyped(value?: TicketAnswers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'questionText': value['questionText'],
        'answer': value['answer'],
    };
}

