/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Timezone = {
    Pst: 'PST',
    Est: 'EST',
    Cst: 'CST',
    Gmt: 'GMT',
    Mst: 'MST'
} as const;
export type Timezone = typeof Timezone[keyof typeof Timezone];


export function instanceOfTimezone(value: any): boolean {
    for (const key in Timezone) {
        if (Object.prototype.hasOwnProperty.call(Timezone, key)) {
            if (Timezone[key as keyof typeof Timezone] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TimezoneFromJSON(json: any): Timezone {
    return TimezoneFromJSONTyped(json, false);
}

export function TimezoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timezone {
    return json as Timezone;
}

export function TimezoneToJSON(value?: Timezone | null): any {
    return value as any;
}

export function TimezoneToJSONTyped(value: any, ignoreDiscriminator: boolean): Timezone {
    return value as Timezone;
}

