/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User1
 */
export interface User1 {
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    profilePic: string;
}

/**
 * Check if a given object implements the User1 interface.
 */
export function instanceOfUser1(value: object): value is User1 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('profilePic' in value) || value['profilePic'] === undefined) return false;
    return true;
}

export function User1FromJSON(json: any): User1 {
    return User1FromJSONTyped(json, false);
}

export function User1FromJSONTyped(json: any, ignoreDiscriminator: boolean): User1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'profilePic': json['profilePic'],
    };
}

export function User1ToJSON(json: any): User1 {
    return User1ToJSONTyped(json, false);
}

export function User1ToJSONTyped(value?: User1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'profilePic': value['profilePic'],
    };
}

