/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Phone } from './Phone';
import {
    PhoneFromJSON,
    PhoneFromJSONTyped,
    PhoneToJSON,
    PhoneToJSONTyped,
} from './Phone';

/**
 * 
 * @export
 * @interface UserContact
 */
export interface UserContact {
    /**
     * 
     * @type {string}
     * @memberof UserContact
     */
    id?: string;
    /**
     * An object describing the email address
     * @type {string}
     * @memberof UserContact
     */
    email: string;
    /**
     * 
     * @type {Phone}
     * @memberof UserContact
     */
    phone?: Phone;
    /**
     * 
     * @type {string}
     * @memberof UserContact
     */
    username: string;
}

/**
 * Check if a given object implements the UserContact interface.
 */
export function instanceOfUserContact(value: object): value is UserContact {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserContactFromJSON(json: any): UserContact {
    return UserContactFromJSONTyped(json, false);
}

export function UserContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : PhoneFromJSON(json['phone']),
        'username': json['username'],
    };
}

export function UserContactToJSON(json: any): UserContact {
    return UserContactToJSONTyped(json, false);
}

export function UserContactToJSONTyped(value?: UserContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'phone': PhoneToJSON(value['phone']),
        'username': value['username'],
    };
}

