/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Social } from './Social';
import {
    SocialFromJSON,
    SocialFromJSONTyped,
    SocialToJSON,
    SocialToJSONTyped,
} from './Social';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Timezone } from './Timezone';
import {
    TimezoneFromJSON,
    TimezoneFromJSONTyped,
    TimezoneToJSON,
    TimezoneToJSONTyped,
} from './Timezone';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { ModelDate } from './ModelDate';
import {
    ModelDateFromJSON,
    ModelDateFromJSONTyped,
    ModelDateToJSON,
    ModelDateToJSONTyped,
} from './ModelDate';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    profilePic?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    backgroundPic?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    bio?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    interests?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    finfluencer?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    moneyPersonality?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    industry?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    city?: string;
    /**
     * 
     * @type {Social}
     * @memberof User
     */
    socials?: Social;
    /**
     * 
     * @type {Timezone}
     * @memberof User
     */
    timezone?: Timezone;
    /**
     * 
     * @type {Address}
     * @memberof User
     */
    address?: Address;
    /**
     * 
     * @type {Status}
     * @memberof User
     */
    status?: Status;
    /**
     * 
     * @type {ModelDate}
     * @memberof User
     */
    createdAt?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof User
     */
    modifiedAt?: ModelDate;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    subscribePrice?: number;
}



/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'profilePic': json['profilePic'] == null ? undefined : json['profilePic'],
        'backgroundPic': json['backgroundPic'] == null ? undefined : json['backgroundPic'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'interests': json['interests'] == null ? undefined : json['interests'],
        'finfluencer': json['finfluencer'] == null ? undefined : json['finfluencer'],
        'moneyPersonality': json['moneyPersonality'] == null ? undefined : json['moneyPersonality'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'city': json['city'] == null ? undefined : json['city'],
        'socials': json['socials'] == null ? undefined : SocialFromJSON(json['socials']),
        'timezone': json['timezone'] == null ? undefined : TimezoneFromJSON(json['timezone']),
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
        'createdAt': json['createdAt'] == null ? undefined : ModelDateFromJSON(json['createdAt']),
        'modifiedAt': json['modifiedAt'] == null ? undefined : ModelDateFromJSON(json['modifiedAt']),
        'subscribePrice': json['subscribePrice'] == null ? undefined : json['subscribePrice'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'profilePic': value['profilePic'],
        'backgroundPic': value['backgroundPic'],
        'bio': value['bio'],
        'interests': value['interests'],
        'finfluencer': value['finfluencer'],
        'moneyPersonality': value['moneyPersonality'],
        'industry': value['industry'],
        'city': value['city'],
        'socials': SocialToJSON(value['socials']),
        'timezone': TimezoneToJSON(value['timezone']),
        'address': AddressToJSON(value['address']),
        'status': StatusToJSON(value['status']),
        'createdAt': ModelDateToJSON(value['createdAt']),
        'modifiedAt': ModelDateToJSON(value['modifiedAt']),
        'subscribePrice': value['subscribePrice'],
    };
}

