/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Blog,
  Blog1,
} from '../models/index';
import {
    BlogFromJSON,
    BlogToJSON,
    Blog1FromJSON,
    Blog1ToJSON,
} from '../models/index';

export interface GetBlogByIdRequest {
    blogId: string;
}

export interface GetPublishedBlogsRequest {
    communityIds?: Array<string>;
    userIds?: Array<string>;
    slugNames?: Array<string>;
    tags?: Array<string>;
}

export interface ShareBlogFarcasterRequest {
    blog: Blog;
}

export interface UploadToIPFSRequest {
    blog: Blog;
}

/**
 * 
 */
export class BlogApi extends runtime.BaseAPI {

    /**
     * Get blog by id
     */
    async getBlogByIdRaw(requestParameters: GetBlogByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Blog>>> {
        if (requestParameters['blogId'] == null) {
            throw new runtime.RequiredError(
                'blogId',
                'Required parameter "blogId" was null or undefined when calling getBlogById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blogs/blog/{blog-id}`.replace(`{${"blog-id"}}`, encodeURIComponent(String(requestParameters['blogId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BlogFromJSON));
    }

    /**
     * Get blog by id
     */
    async getBlogById(requestParameters: GetBlogByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Blog>> {
        const response = await this.getBlogByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all published blogs that fit the query
     */
    async getPublishedBlogsRaw(requestParameters: GetPublishedBlogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Blog1>>> {
        const queryParameters: any = {};

        if (requestParameters['communityIds'] != null) {
            queryParameters['communityIds'] = requestParameters['communityIds'];
        }

        if (requestParameters['userIds'] != null) {
            queryParameters['userIds'] = requestParameters['userIds'];
        }

        if (requestParameters['slugNames'] != null) {
            queryParameters['slugNames'] = requestParameters['slugNames'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blogs/published-blogs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(Blog1FromJSON));
    }

    /**
     * Get all published blogs that fit the query
     */
    async getPublishedBlogs(requestParameters: GetPublishedBlogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Blog1>> {
        const response = await this.getPublishedBlogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Share on Blog on Farcaster
     */
    async shareBlogFarcasterRaw(requestParameters: ShareBlogFarcasterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['blog'] == null) {
            throw new runtime.RequiredError(
                'blog',
                'Required parameter "blog" was null or undefined when calling shareBlogFarcaster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blogs/share-farcaster`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BlogToJSON(requestParameters['blog']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Share on Blog on Farcaster
     */
    async shareBlogFarcaster(requestParameters: ShareBlogFarcasterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.shareBlogFarcasterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Blog to IPFS
     */
    async uploadToIPFSRaw(requestParameters: UploadToIPFSRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['blog'] == null) {
            throw new runtime.RequiredError(
                'blog',
                'Required parameter "blog" was null or undefined when calling uploadToIPFS().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blogs/upload-ipfs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BlogToJSON(requestParameters['blog']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload Blog to IPFS
     */
    async uploadToIPFS(requestParameters: UploadToIPFSRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.uploadToIPFSRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
