/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Donation,
  Event,
  EventSlot,
  EventSponsor,
  Host,
  PromoCode,
  Ticket,
} from '../models/index';
import {
    DonationFromJSON,
    DonationToJSON,
    EventFromJSON,
    EventToJSON,
    EventSlotFromJSON,
    EventSlotToJSON,
    EventSponsorFromJSON,
    EventSponsorToJSON,
    HostFromJSON,
    HostToJSON,
    PromoCodeFromJSON,
    PromoCodeToJSON,
    TicketFromJSON,
    TicketToJSON,
} from '../models/index';

export interface AddHostRequest {
    eventSlotId: string;
    host: Host;
}

export interface AddPromoCodeRequest {
    eventSlotId: string;
    promoCode: PromoCode;
}

export interface AddSponsorRequest {
    eventSlotId: string;
    eventSponsor: EventSponsor;
}

export interface CreateEventRequest {
    event: Event;
}

export interface CreateEventSlotRequest {
    eventSlot: EventSlot;
}

export interface CreateTicketRequest {
    ticket: Ticket;
}

export interface DeleteEventRequest {
    eventId: string;
}

export interface DeleteEventSlotRequest {
    eventSlotId: string;
}

export interface DonateEventRequest {
    eventSlotId: string;
    donation: Donation;
}

export interface GetEventSlotTicketEmailsRequest {
    eventSlotId: string;
}

export interface GetEventSlotTicketsRequest {
    eventSlotId: string;
}

export interface GetTicketsRequest {
    userId: string;
    eventId: string;
}

export interface GetUserEventSlotTicketsRequest {
    eventSlotId: string;
    userId: string;
}

export interface UpdateEventRequest {
    event: Event;
}

export interface UpdateEventSlotRequest {
    eventSlot: EventSlot;
}

export interface UserEventsRequest {
    userId: string;
}

/**
 * 
 */
export class EventApi extends runtime.BaseAPI {

    /**
     * Add Host
     */
    async addHostRaw(requestParameters: AddHostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling addHost().'
            );
        }

        if (requestParameters['host'] == null) {
            throw new runtime.RequiredError(
                'host',
                'Required parameter "host" was null or undefined when calling addHost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/add-host`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HostToJSON(requestParameters['host']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Host
     */
    async addHost(requestParameters: AddHostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.addHostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add Promo
     */
    async addPromoCodeRaw(requestParameters: AddPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling addPromoCode().'
            );
        }

        if (requestParameters['promoCode'] == null) {
            throw new runtime.RequiredError(
                'promoCode',
                'Required parameter "promoCode" was null or undefined when calling addPromoCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/add-promo-code`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PromoCodeToJSON(requestParameters['promoCode']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Promo
     */
    async addPromoCode(requestParameters: AddPromoCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.addPromoCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add Host
     */
    async addSponsorRaw(requestParameters: AddSponsorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling addSponsor().'
            );
        }

        if (requestParameters['eventSponsor'] == null) {
            throw new runtime.RequiredError(
                'eventSponsor',
                'Required parameter "eventSponsor" was null or undefined when calling addSponsor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/add-sponsor`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventSponsorToJSON(requestParameters['eventSponsor']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add Host
     */
    async addSponsor(requestParameters: AddSponsorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.addSponsorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an event
     * Create an event
     */
    async createEventRaw(requestParameters: CreateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        if (requestParameters['event'] == null) {
            throw new runtime.RequiredError(
                'event',
                'Required parameter "event" was null or undefined when calling createEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/create-event`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventToJSON(requestParameters['event']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Create an event
     * Create an event
     */
    async createEvent(requestParameters: CreateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.createEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an event slot
     */
    async createEventSlotRaw(requestParameters: CreateEventSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSlot>> {
        if (requestParameters['eventSlot'] == null) {
            throw new runtime.RequiredError(
                'eventSlot',
                'Required parameter "eventSlot" was null or undefined when calling createEventSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/create-event-slot`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventSlotToJSON(requestParameters['eventSlot']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSlotFromJSON(jsonValue));
    }

    /**
     * Create an event slot
     */
    async createEventSlot(requestParameters: CreateEventSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSlot> {
        const response = await this.createEventSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Ticket
     */
    async createTicketRaw(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['ticket'] == null) {
            throw new runtime.RequiredError(
                'ticket',
                'Required parameter "ticket" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/create-ticket`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketToJSON(requestParameters['ticket']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Ticket
     */
    async createTicket(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Event
     */
    async deleteEventRaw(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling deleteEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/delete-event/{event-id}`.replace(`{${"event-id"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Event
     */
    async deleteEvent(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deleteEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Event Slot
     */
    async deleteEventSlotRaw(requestParameters: DeleteEventSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling deleteEventSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/delete-event-slot/{event-slot-id}`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Event Slot
     */
    async deleteEventSlot(requestParameters: DeleteEventSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deleteEventSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Donate Event
     */
    async donateEventRaw(requestParameters: DonateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling donateEvent().'
            );
        }

        if (requestParameters['donation'] == null) {
            throw new runtime.RequiredError(
                'donation',
                'Required parameter "donation" was null or undefined when calling donateEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/donate`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DonationToJSON(requestParameters['donation']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Donate Event
     */
    async donateEvent(requestParameters: DonateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.donateEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all emails of ticket holders for an event slot
     */
    async getEventSlotTicketEmailsRaw(requestParameters: GetEventSlotTicketEmailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling getEventSlotTicketEmails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/get-event-slot-ticket-emails/{event-slot-id}`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all emails of ticket holders for an event slot
     */
    async getEventSlotTicketEmails(requestParameters: GetEventSlotTicketEmailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getEventSlotTicketEmailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all tickets for an event slot
     */
    async getEventSlotTicketsRaw(requestParameters: GetEventSlotTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Ticket>>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling getEventSlotTickets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/get-event-slot-tickets/{event-slot-id}`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketFromJSON));
    }

    /**
     * Get all tickets for an event slot
     */
    async getEventSlotTickets(requestParameters: GetEventSlotTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Ticket>> {
        const response = await this.getEventSlotTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all events that fit the query
     */
    async getTicketsRaw(requestParameters: GetTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Ticket>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getTickets().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getTickets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/get-ticket/{ticket-id}`.replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"event-id"}}`, encodeURIComponent(String(requestParameters['eventId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketFromJSON));
    }

    /**
     * Get all events that fit the query
     */
    async getTickets(requestParameters: GetTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Ticket>> {
        const response = await this.getTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all tickets for user for an event slot
     */
    async getUserEventSlotTicketsRaw(requestParameters: GetUserEventSlotTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Ticket>>> {
        if (requestParameters['eventSlotId'] == null) {
            throw new runtime.RequiredError(
                'eventSlotId',
                'Required parameter "eventSlotId" was null or undefined when calling getUserEventSlotTickets().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserEventSlotTickets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/get-user-event-slot-tickets/{event-slot-id}/{user-id}`.replace(`{${"event-slot-id"}}`, encodeURIComponent(String(requestParameters['eventSlotId']))).replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketFromJSON));
    }

    /**
     * Get all tickets for user for an event slot
     */
    async getUserEventSlotTickets(requestParameters: GetUserEventSlotTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Ticket>> {
        const response = await this.getUserEventSlotTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an event
     */
    async updateEventRaw(requestParameters: UpdateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        if (requestParameters['event'] == null) {
            throw new runtime.RequiredError(
                'event',
                'Required parameter "event" was null or undefined when calling updateEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/update-event`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventToJSON(requestParameters['event']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Update an event
     */
    async updateEvent(requestParameters: UpdateEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.updateEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an event slot
     */
    async updateEventSlotRaw(requestParameters: UpdateEventSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSlot>> {
        if (requestParameters['eventSlot'] == null) {
            throw new runtime.RequiredError(
                'eventSlot',
                'Required parameter "eventSlot" was null or undefined when calling updateEventSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/events/update-event-slot`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventSlotToJSON(requestParameters['eventSlot']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSlotFromJSON(jsonValue));
    }

    /**
     * Update an event slot
     */
    async updateEventSlot(requestParameters: UpdateEventSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSlot> {
        const response = await this.updateEventSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all tickets for a user
     */
    async userEventsRaw(requestParameters: UserEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ticket>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userEvents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/events/get-user-events/{user-id}`.replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketFromJSON(jsonValue));
    }

    /**
     * Get all tickets for a user
     */
    async userEvents(requestParameters: UserEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ticket> {
        const response = await this.userEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
