/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeviceTokenRegistration,
  DeviceTokenUnregistration,
  PushNotification,
} from '../models/index';
import {
    DeviceTokenRegistrationFromJSON,
    DeviceTokenRegistrationToJSON,
    DeviceTokenUnregistrationFromJSON,
    DeviceTokenUnregistrationToJSON,
    PushNotificationFromJSON,
    PushNotificationToJSON,
} from '../models/index';

export interface PushNotificationRequest {
    pushNotification: PushNotification;
}

export interface RegisterDeviceTokenRequest {
    deviceTokenRegistration: DeviceTokenRegistration;
}

export interface TestPushNotificationRequest {
    pushNotification: PushNotification;
}

export interface UnregisterDeviceTokenRequest {
    deviceTokenUnregistration: DeviceTokenUnregistration;
}

/**
 * 
 */
export class PushNotificationApi extends runtime.BaseAPI {

    /**
     * Push Notification
     */
    async pushNotificationRaw(requestParameters: PushNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['pushNotification'] == null) {
            throw new runtime.RequiredError(
                'pushNotification',
                'Required parameter "pushNotification" was null or undefined when calling pushNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/push-notification/push-notification`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PushNotificationToJSON(requestParameters['pushNotification']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Push Notification
     */
    async pushNotification(requestParameters: PushNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pushNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a device token
     */
    async registerDeviceTokenRaw(requestParameters: RegisterDeviceTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['deviceTokenRegistration'] == null) {
            throw new runtime.RequiredError(
                'deviceTokenRegistration',
                'Required parameter "deviceTokenRegistration" was null or undefined when calling registerDeviceToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/push-notification/register-device-token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceTokenRegistrationToJSON(requestParameters['deviceTokenRegistration']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Register a device token
     */
    async registerDeviceToken(requestParameters: RegisterDeviceTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.registerDeviceTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Test push notification
     */
    async testPushNotificationRaw(requestParameters: TestPushNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['pushNotification'] == null) {
            throw new runtime.RequiredError(
                'pushNotification',
                'Required parameter "pushNotification" was null or undefined when calling testPushNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/push-notification/test-push-notification`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PushNotificationToJSON(requestParameters['pushNotification']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Test push notification
     */
    async testPushNotification(requestParameters: TestPushNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.testPushNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unregister a device token
     */
    async unregisterDeviceTokenRaw(requestParameters: UnregisterDeviceTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['deviceTokenUnregistration'] == null) {
            throw new runtime.RequiredError(
                'deviceTokenUnregistration',
                'Required parameter "deviceTokenUnregistration" was null or undefined when calling unregisterDeviceToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/push-notification/unregister-device-token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceTokenUnregistrationToJSON(requestParameters['deviceTokenUnregistration']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Unregister a device token
     */
    async unregisterDeviceToken(requestParameters: UnregisterDeviceTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.unregisterDeviceTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
