/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Actions,
  GetTopScoreUsers200ResponseInner,
  PointsGift,
  ScoreLedger,
} from '../models/index';
import {
    ActionsFromJSON,
    ActionsToJSON,
    GetTopScoreUsers200ResponseInnerFromJSON,
    GetTopScoreUsers200ResponseInnerToJSON,
    PointsGiftFromJSON,
    PointsGiftToJSON,
    ScoreLedgerFromJSON,
    ScoreLedgerToJSON,
} from '../models/index';

export interface GetScoreRequest {
    userId: string;
}

export interface GetScoreLedgerRequest {
    userId: string;
}

export interface GivePointsRequest {
    pointsGift: PointsGift;
}

export interface UpdateScoreRequest {
    userId: string;
    score: number;
}

export interface UpdateScoreActionRequest {
    userId: string;
    actions: Actions;
}

/**
 * 
 */
export class ScoreApi extends runtime.BaseAPI {

    /**
     * Get score
     */
    async getScoreRaw(requestParameters: GetScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getScore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/score/get-score/{user-id}`.replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get score
     */
    async getScore(requestParameters: GetScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getScoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get score ledger
     */
    async getScoreLedgerRaw(requestParameters: GetScoreLedgerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScoreLedger>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getScoreLedger().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/score/get-score-ledger/{user-id}`.replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScoreLedgerFromJSON));
    }

    /**
     * Get score ledger
     */
    async getScoreLedger(requestParameters: GetScoreLedgerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScoreLedger>> {
        const response = await this.getScoreLedgerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get top score users with their scores
     */
    async getTopScoreUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetTopScoreUsers200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/score/top-users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetTopScoreUsers200ResponseInnerFromJSON));
    }

    /**
     * Get top score users with their scores
     */
    async getTopScoreUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetTopScoreUsers200ResponseInner>> {
        const response = await this.getTopScoreUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a score
     */
    async givePointsRaw(requestParameters: GivePointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['pointsGift'] == null) {
            throw new runtime.RequiredError(
                'pointsGift',
                'Required parameter "pointsGift" was null or undefined when calling givePoints().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/score/give-points/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PointsGiftToJSON(requestParameters['pointsGift']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update a score
     */
    async givePoints(requestParameters: GivePointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.givePointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a score
     */
    async updateScoreRaw(requestParameters: UpdateScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateScore().'
            );
        }

        if (requestParameters['score'] == null) {
            throw new runtime.RequiredError(
                'score',
                'Required parameter "score" was null or undefined when calling updateScore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/score/update-score/{user-id}/{score}`.replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"score"}}`, encodeURIComponent(String(requestParameters['score']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update a score
     */
    async updateScore(requestParameters: UpdateScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.updateScoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a score with an Action
     */
    async updateScoreActionRaw(requestParameters: UpdateScoreActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateScoreAction().'
            );
        }

        if (requestParameters['actions'] == null) {
            throw new runtime.RequiredError(
                'actions',
                'Required parameter "actions" was null or undefined when calling updateScoreAction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/score/update-score-action/{user-id}/{actions}`.replace(`{${"user-id"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"actions"}}`, encodeURIComponent(String(requestParameters['actions']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update a score with an Action
     */
    async updateScoreAction(requestParameters: UpdateScoreActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.updateScoreActionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
