/* tslint:disable */
/* eslint-disable */
/**
 * ChaChing Social Social API
 * FatFIRESocial is a social network for people who are interested in financial independence and early retirement. It is a place to share your journey, ask questions, and connect with others who are on the same path. Whether you are just starting out or have already achieved financial independence, FatFIRESocial is a community where you can find support, inspiration, and advice. Join us today and start building the life you want! ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mabel.oza@chachingsocial.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetCryptoPricingRequest {
    cryptoId: Array<GetCryptoPricingCryptoIdEnum>;
    currency: GetCryptoPricingCurrencyEnum;
}

/**
 * 
 */
export class Web3Api extends runtime.BaseAPI {

    /**
     * Get crypto pricing
     */
    async getCryptoPricingRaw(requestParameters: GetCryptoPricingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: number; }>> {
        if (requestParameters['cryptoId'] == null) {
            throw new runtime.RequiredError(
                'cryptoId',
                'Required parameter "cryptoId" was null or undefined when calling getCryptoPricing().'
            );
        }

        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling getCryptoPricing().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cryptoId'] != null) {
            queryParameters['crypto_id'] = requestParameters['cryptoId'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/web3/crypto-pricing`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get crypto pricing
     */
    async getCryptoPricing(requestParameters: GetCryptoPricingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: number; }> {
        const response = await this.getCryptoPricingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetCryptoPricingCryptoIdEnum = {
    Bitcoin: 'bitcoin',
    Ethereum: 'ethereum',
    Solana: 'solana',
    Sui: 'sui',
    Base: 'base'
} as const;
export type GetCryptoPricingCryptoIdEnum = typeof GetCryptoPricingCryptoIdEnum[keyof typeof GetCryptoPricingCryptoIdEnum];
/**
 * @export
 */
export const GetCryptoPricingCurrencyEnum = {
    Usd: 'usd',
    Eur: 'eur',
    Gbp: 'gbp',
    Jpy: 'jpy',
    Aud: 'aud'
} as const;
export type GetCryptoPricingCurrencyEnum = typeof GetCryptoPricingCurrencyEnum[keyof typeof GetCryptoPricingCurrencyEnum];
